'use strict';
const m=require('./model'),csv=require('./contact_csv');
function createContactPortability({db,authority,now=Date.now}){
 const root=b=>db.doc('businessOperations/'+m.id(b));
 const requirePermission=(a,p)=>{if(!a.isOwner&&!a.permissions.includes(p))m.fail('permission-denied','Your team access does not include contact '+p+'.');};
 async function contacts(b,tx){const q=root(b).collection('customers').limit(1001),s=await(tx?tx.get(q):q.get());if(s.size>1000)m.fail('resource-exhausted','This workspace exceeds the current 1000-contact limit. Nothing was truncated.');return s.docs.map(d=>({id:d.id,...d.data()}));}
 async function execute(request){const op=request.data.operation,input=request.data.input||{},write=!['exportContacts','inspectContactCsv','listContactImports'].includes(op);const a=await authority(request,{write});requirePermission(a,'customersView');if(write)requirePermission(a,'customersEdit');
 if(op==='listContactImports'){m.strict(input,[]);const s=await root(a.businessId).collection('contactImports').orderBy('createdAtMs','desc').limit(50).get();return {imports:s.docs.filter(d=>d.data().actorUid===a.actorUid).map(d=>{const v=d.data();return {id:d.id,filename:v.filename,status:v.status,createdAtMs:v.createdAtMs,receipt:v.receipt||null,decisions:v.status==='importing'?v.decisions:null};})};}
 if(op==='inspectContactCsv'){m.strict(input,['csv']);const parsed=csv.parse(input.csv);return {headers:parsed.headers,mapping:csv.detect(parsed.headers),fields:csv.FIELDS,rowCount:parsed.rows.length};}
 if(op==='exportContacts'){m.strict(input,['search','filter']);const query=m.text(input.search||'',180).toLowerCase(),filter=m.choice(input.filter||'All',['All','Needs follow-up','Won','Lost']);const all=await contacts(a.businessId);const selected=all.filter(c=>['name','company','email','phone','location'].map(k=>c[k]||'').join(' ').toLowerCase().includes(query)).filter(c=>filter==='All'||filter==='Needs follow-up'&&['follow_up','estimate_given'].includes(c.stage)||filter==='Won'&&c.stage==='won'||filter==='Lost'&&c.stage==='lost');const owner=await db.doc('users/'+a.businessId).get(),members=await db.collection(`businessWorkspaces/${a.businessId}/members`).get(),resources=await root(a.businessId).collection('resources').get(),suppression=await db.collection(`businessMailboxes/${a.businessId}/suppression`).where('active','==',true).limit(1001).get();if(suppression.size>1000)m.fail('resource-exhausted','Suppression inventory exceeds export limit.');const restricted=new Set(suppression.docs.map(d=>d.data().recipient)),names=new Map([['user:'+a.businessId,owner.data()?.displayName||owner.data()?.name||owner.data()?.companyName||'Business owner'],...members.docs.map(d=>['user:'+d.id,d.data().name||'Team member']),...resources.docs.map(d=>['crew:'+d.id,d.data().name||'Crew'])]);const output=selected.map(c=>({...c,suppressed:restricted.has(c.email),assignedOwnerNames:(c.assignedPeople||[]).map(id=>names.get(id)||'Former member').join('; ')}));await root(a.businessId).collection('contactExports').add({actorUid:a.actorUid,createdAtMs:now(),count:output.length,filter,search:query,schema:csv.SCHEMA});return {csv:csv.exportCsv(output),count:output.length,filename:'scaledcircle-contacts-'+new Date(now()).toISOString().slice(0,10)+'.csv'};}
 if(op==='previewContactImport'){m.strict(input,['csv','mapping','filename']);const filename=m.text(input.filename||'contacts.csv',160,true),ref=root(a.businessId).collection('contactImports').doc();return db.runTransaction(async tx=>{const current=await authority(request,{write:true,transaction:tx});requirePermission(current,'customersEdit');requirePermission(current,'customersView');const meta=await tx.get(root(a.businessId)),all=await contacts(a.businessId,tx);const plan=csv.plan(input.csv,input.mapping,all);const value={...plan,actorUid:a.actorUid,businessId:a.businessId,filename,fileHash:m.hash(input.csv),revision:meta.data()?.revision||0,createdAtMs:now(),expiresAtMs:now()+3600000,status:'preview'};if(Buffer.byteLength(JSON.stringify(value))>800000)m.fail('resource-exhausted','Preview is too large. Split this file into smaller files.');tx.create(ref,value);return {previewId:ref.id,rows:plan.rows,expiresAtMs:value.expiresAtMs};});}
 if(op!=='commitContactImport')m.fail('invalid-argument','Unsupported contact operation.');m.strict(input,['previewId','decisions','confirmed']);if(input.confirmed!==true||!Array.isArray(input.decisions))m.fail('invalid-argument','Confirm the reviewed import decisions.');const previewRef=root(a.businessId).collection('contactImports').doc(m.id(input.previewId));
 return db.runTransaction(async tx=>{const currentAuthority=await authority(request,{write:true,transaction:tx});requirePermission(currentAuthority,'customersView');requirePermission(currentAuthority,'customersEdit');const snapshot=await tx.get(previewRef),preview=snapshot.data();if(!preview||preview.actorUid!==a.actorUid)m.fail('permission-denied','Choose your own import preview.');if(preview.status==='committed')return {...preview.receipt,replayed:true};
 const meta=await tx.get(root(a.businessId));if(preview.expiresAtMs<now()||preview.revision!==(meta.data()?.revision||0))m.fail('aborted','Contacts changed or preview expired. Preview again.');if(preview.decisionsHash&&preview.decisionsHash!==m.hash(input.decisions))m.fail('invalid-argument','Keep the same confirmed decisions when resuming this import.');if(input.decisions.length!==preview.rows.length)m.fail('invalid-argument','Review every row.');const all=await contacts(a.businessId,tx),members=await tx.get(db.collection(`businessWorkspaces/${a.businessId}/members`)),resources=await tx.get(root(a.businessId).collection('resources'));
 const allowed=new Set(['user:'+a.businessId,...members.docs.filter(d=>d.data().status==='active'&&d.data().seatIndex>0&&d.data().seatIndex<currentAuthority.capacity).map(d=>'user:'+d.id),...resources.docs.filter(d=>d.data().status==='active').map(d=>'crew:'+d.id)]);
 const receipt=preview.receipt||{processed:0,created:0,matched:0,updated:0,skipped:0,duplicate:0,failed:0,unauthorizedWrites:0,previewId:input.previewId};let count=all.length;const writes=[];
 const start=preview.cursor||0,end=Math.min(start+100,preview.rows.length);for(let i=start;i<end;i++){receipt.processed++;const row=preview.rows[i],decision=m.choice(input.decisions[i],['create','update','skip']);if(row.kind==='invalid'){if(decision!=='skip')m.fail('invalid-argument','Skip invalid rows.');receipt.failed++;continue;}if(row.matchId)receipt.matched++;
 if(row.kind==='duplicate'){if(decision!=='skip')m.fail('invalid-argument','Skip duplicate rows.');receipt.duplicate++;receipt.skipped++;continue;}if(decision==='skip'){receipt.skipped++;continue;}if((decision==='create')!==(row.kind==='new'))m.fail('invalid-argument','Only create new contacts; only update reviewed matches.');const current=row.matchId?all.find(c=>c.id===row.matchId):null;
 const base=Object.fromEntries(Object.entries(current||{}).filter(([k])=>['name','company','phone','email','location','source','stage','notes','assignedPeople',...csv.EXTRA].includes(k)));const value=m.customer({...base,...row.supplied});if(value.assignedPeople.some(p=>!allowed.has(p)))m.fail('invalid-argument','Choose a current workspace owner.');if(JSON.stringify(value.assignedPeople)!==JSON.stringify(current?.assignedPeople||[]))requirePermission(currentAuthority,'assignPeople');if(current&&current.version!==row.expectedVersion)m.fail('aborted','A matched contact changed. Preview the remaining rows again.');if(!current&&++count>1000)m.fail('resource-exhausted','Contact limit reached. No rows committed.');const id=current?.id||'customer_'+m.hash([input.previewId,row.row]);
 writes.push({id,value:{...current,...value,businessId:a.businessId,version:(current?.version||0)+1,createdAtMs:current?.createdAtMs||now(),updatedAtMs:now(),updatedBy:a.actorUid,lastImportId:input.previewId},row:row.row,kind:current?'customer_updated':'customer_created'});receipt[current?'updated':'created']++;
 }
 for(const w of writes){tx.set(root(a.businessId).collection('customers').doc(w.id),w.value);tx.create(root(a.businessId).collection('timeline').doc(input.previewId+'_'+w.row),{customerId:w.id,kind:w.kind,summary:'CSV contact import',actorUid:a.actorUid,atMs:now(),evidenceType:'owner_supplied_csv',details:{importId:input.previewId,row:w.row,sourceName:preview.filename,sourceHash:preview.fileHash}});}
 const done=end===preview.rows.length;receipt.complete=done;tx.update(previewRef,{status:done?'committed':'importing',receipt,cursor:end,decisions:input.decisions,decisionsHash:m.hash(input.decisions),revision:(meta.data()?.revision||0)+1,...(done?{committedAtMs:now()}:{})});tx.set(root(a.businessId),{revision:(meta.data()?.revision||0)+1,updatedAtMs:now()},{merge:true});return receipt;});
 }
 return {execute};
}
module.exports={createContactPortability};
