'use strict';
// Reviewed source references join the canonical customer; they do not grant outreach consent.
const m=require('./model');
const permission=(a,p)=>{if(!a.isOwner&&!a.permissions.includes(p))m.fail('permission-denied','Source access is not included in your workspace permissions.');};
function sourceRef(db,b,kind,id){m.id(id);if(kind==='email_candidate')return db.doc(`businessMailboxes/${b}/campaignCandidates/${id}`);if(kind==='agent_prospect')return db.doc('agentProspects/'+id);m.fail('invalid-argument','Choose a supported saved source.');}
function project(kind,id,s,b){if((kind==='email_candidate'?s.businessId:s.businessUid)!==b)m.fail('permission-denied','Source belongs to another Business.');return {kind,id,name:s.name||s.companyName||s.businessName||s.email||'',email:s.email||'',company:s.companyName||s.businessName||'',source:kind==='email_candidate'?'Reviewed Email discovery':'Reviewed agent prospect',restricted:s.doNotContact===true||['suppressed','unsubscribed','do_not_contact','excluded_automated'].includes(s.status||s.lifecycleState),sourceDate:s.createdAt?.toMillis?.()||s.createdAt||null};}
async function execute({db,authority,request,now=Date.now}){
 const input=request.data.input||{},write=request.data.operation==='importContactSource',a=await authority(request,{write});permission(a,'customersView');if(write)permission(a,'customersEdit');
 m.strict(input,write?['kind','id','confirmed']:['kind']);m.choice(input.kind,['email_candidate','agent_prospect']);const required=input.kind==='email_candidate'?'communicationsRead':'intelligence';permission(a,required);
 if(!write){const q=input.kind==='email_candidate'?db.collection(`businessMailboxes/${a.businessId}/campaignCandidates`).limit(101):db.collection('agentProspects').where('businessUid','==',a.businessId).limit(101),snap=await q.get();if(snap.size>100)m.fail('resource-exhausted','Review the source inventory before importing.');return {sources:snap.docs.map(d=>project(input.kind,d.id,d.data(),a.businessId))};}
 if(input.confirmed!==true)m.fail('invalid-argument','Review and confirm this source.');const source=sourceRef(db,a.businessId,input.kind,input.id),root=db.doc('businessOperations/'+a.businessId);
 return db.runTransaction(async tx=>{const current=await authority(request,{write:true,transaction:tx});for(const p of ['customersView','customersEdit',required])permission(current,p);const s=(await tx.get(source)).data();if(!s)m.fail('not-found','Source no longer exists.');const row=project(input.kind,input.id,s,a.businessId),meta=await tx.get(root),all=await tx.get(root.collection('customers').limit(1001));if(all.size>1000)m.fail('resource-exhausted','Contact inventory exceeds the supported limit.');const value=m.customer({name:row.name,email:row.email,company:row.company,source:row.source});const keys=m.contactKeys(value),matches=all.docs.filter(d=>m.contactKeys(d.data()).some(k=>keys.includes(k)));if(matches.length>1)m.fail('failed-precondition','Resolve duplicate customer identities first.');const existing=matches[0],id=existing?.id||'source_'+m.hash([input.kind,input.id]);if(!existing&&all.size>=1000)m.fail('resource-exhausted','Contact limit reached.');const old=existing?.data(),provenance={kind:input.kind,id:input.id},sources=old?.linkedContactSources||[];if(sources.some(x=>x.kind===input.kind&&x.id===input.id))return {customerId:id,created:false,replayed:true,sent:0};if(sources.length>=50)m.fail('resource-exhausted','Contact provenance needs review.');
 tx.set(root.collection('customers').doc(id),{...(old||value),businessId:a.businessId,linkedContactSources:[...sources,provenance],...(!old?{sourceRef:provenance,createdAtMs:now()}:{}),...(row.restricted?{doNotContact:true}:{}),version:(old?.version||0)+1,updatedAtMs:now(),updatedBy:a.actorUid});tx.create(root.collection('timeline').doc(),{customerId:id,kind:'source_linked',summary:row.source,actorUid:a.actorUid,atMs:now(),details:provenance});tx.set(root,{revision:(meta.data()?.revision||0)+1,updatedAtMs:now()},{merge:true});return {customerId:id,created:!existing,sent:0};});
}
module.exports={execute,project};
