'use strict';
const m=require('./model');
const SCHEMA='ScaledCircleContactsV1', MAX_ROWS=1000, MAX_BYTES=256000;
const FIELDS={id:'Contact ID',category:'Contact category',name:'Customer name',company:'Company',phone:'Phone',email:'Email',location:'Service address',serviceNeeded:'Service needed',interest:'Area of interest',projectDetails:'Project details',estimatedValue:'Estimated project value',estimatedBudget:'Estimated budget',source:'Lead source',attribution:'Campaign attribution',preferredContactMethod:'Preferred contact method',stage:'Status',assignedPeople:'Assigned owner IDs',notes:'Notes',tags:'Tags',sourceDate:'Source date',createdAtMs:'Created date',updatedAtMs:'Last updated date',lastContactedDate:'Last contacted date',nextFollowUpDate:'Next follow-up date',conversionDate:'Conversion date'};
const EXTRA=['category','serviceNeeded','interest','projectDetails','estimatedValue','estimatedBudget','attribution','preferredContactMethod','tags','sourceDate','lastContactedDate','nextFollowUpDate','conversionDate'];
function parse(csv){
 if(typeof csv!=='string'||Buffer.byteLength(csv,'utf8')>MAX_BYTES||csv.includes('\0')||csv.includes('\uFFFD'))m.fail('invalid-argument','Use a valid UTF-8 CSV file no larger than 256 KB.');
 csv=csv.replace(/^\uFEFF/,'');const rows=[];let row=[],cell='',quoted=false,closed=false;
 const end=()=>{row.push(cell);if(row.some(x=>x!==''))rows.push(row);row=[];cell='';closed=false;if(rows.length>MAX_ROWS+1)m.fail('resource-exhausted','Import at most 1000 contacts per file.');};
 for(let i=0;i<csv.length;i++){const c=csv[i];if(cell.length>16000)m.fail('resource-exhausted','Oversized field.');if(quoted){if(c==='"'){if(csv[i+1]==='"'){cell+='"';i++;}else{quoted=false;closed=true;}}else cell+=c;continue;}
 if(c==='"'){if(cell||closed)m.fail('invalid-argument','Unexpected quote in CSV.');quoted=true;}
 else if(c===','){row.push(cell);cell='';closed=false;}
 else if(c==='\r'||c==='\n'){if(c==='\r'&&csv[i+1]==='\n')i++;end();}
 else{if(closed)m.fail('invalid-argument','Unexpected text after a quoted field.');cell+=c;}
 if(row.length>40||cell.length>16000)m.fail('resource-exhausted','Too many columns or an oversized field.');}
 if(quoted)m.fail('invalid-argument','CSV has an unterminated quoted field.');end();if(rows.length<2)m.fail('invalid-argument','Include a header and at least one contact row.');
 const headers=rows.shift().map(x=>x.trim());if(headers.length>40||headers.some(x=>!x)||new Set(headers.map(x=>x.toLowerCase())).size!==headers.length)m.fail('invalid-argument','Use distinct, nonempty column headers.');
 return {headers,rows};
}
const canonical=s=>s.toLowerCase().replace(/[^a-z0-9]/g,'');
function detect(headers){const aliases={name:'name',contactname:'name',customer:'name',emailaddress:'email',phonenumber:'phone',address:'location',companyname:'company',leadstatus:'stage',leadsource:'source'};return headers.map(h=>Object.keys(FIELDS).find(k=>canonical(FIELDS[k])===canonical(h))||aliases[canonical(h)]||(h==='CSV schema'?'schema':''));}
function extras(input){const out={};for(const k of EXTRA){if(input[k]===undefined)continue;const v=input[k];if(k==='tags'){if(!Array.isArray(v)||v.length>30||v.some(t=>typeof t!=='string'||t.length>60))m.fail('invalid-argument','Use at most 30 tags of 60 characters.');out[k]=[...new Set(v.map(t=>t.trim()).filter(Boolean))];}else {out[k]=m.text(v,k==='projectDetails'?4000:600);if(k.endsWith('Date')&&out[k]&&(!/^\d{4}-\d{2}-\d{2}(?:T.*Z)?$/.test(out[k])||!Number.isFinite(Date.parse(out[k]))))m.fail('invalid-argument','Use ISO dates (YYYY-MM-DD).');if(['estimatedValue','estimatedBudget'].includes(k)&&out[k]&&!/^\d{1,10}(\.\d{1,2})?$/.test(out[k]))m.fail('invalid-argument','Use a nonnegative amount without a currency symbol.');}}return out;}
const safe=v=>/^[\s]*[=+@\-]|^[\t\r\n']/.test(v)?"'"+v:v;
function plan(csv,mapping,existing){const parsed=parse(csv);if(!Array.isArray(mapping)||mapping.length!==parsed.headers.length||mapping.some(k=>k&&!Object.hasOwn(FIELDS,k)&&k!=='schema')||new Set(mapping.filter(Boolean)).size!==mapping.filter(Boolean).length||!mapping.includes('name'))m.fail('invalid-argument','Map each destination once, including Customer name.');
 const seen=new Set();const rows=parsed.rows.map((cells,i)=>{const result={row:i+2};try{if(cells.length!==mapping.length)m.fail('invalid-argument','Column count differs from header.');const raw={};mapping.forEach((k,j)=>{if(k)raw[k]=cells[j];});if(raw.schema===SCHEMA)for(const k of Object.keys(raw))if(raw[k].startsWith("'")&&safe(raw[k].slice(1))===raw[k])raw[k]=raw[k].slice(1);
 const id=raw.id?m.id(raw.id):null;const supplied={};for(const k of Object.keys(raw))if(!['schema','id','createdAtMs','updatedAtMs'].includes(k))supplied[k]=['tags','assignedPeople'].includes(k)?(raw.schema===SCHEMA&&raw[k].startsWith('[')?JSON.parse(raw[k]):raw[k].split('|').filter(Boolean)):raw[k];
 const normalized=m.customer(supplied),keys=m.contactKeys(normalized);const matches=id?existing.filter(x=>x.id===id):existing.filter(x=>m.contactKeys(x).some(k=>keys.includes(k)));
 if(id&&!matches.length)m.fail('invalid-argument','Contact ID does not exist in this workspace. Ignore Contact ID to import a copy.');if(matches.length>1)m.fail('invalid-argument','Multiple contacts match. Resolve this identity first.');
 const match=matches[0];if(id&&existing.some(x=>x.id!==id&&m.contactKeys(x).some(k=>keys.includes(k))))m.fail('invalid-argument','Changed identity matches another contact. Resolve it first.');const identityKeys=[...keys,...(match?['id:'+match.id]:[])],duplicate=identityKeys.some(k=>seen.has(k));identityKeys.forEach(k=>seen.add(k));
 const changes=match?Object.fromEntries(Object.entries(supplied).filter(([k,v])=>JSON.stringify(match[k]??(Array.isArray(v)?[]:''))!==JSON.stringify(v))):supplied;
 return {...result,values:normalized,supplied,matchId:match?.id||null,expectedVersion:match?.version||0,changes,kind:duplicate?'duplicate':match?(Object.keys(changes).length?'matched':'unchanged'):'new',name:normalized.name};
 }catch(e){if(e instanceof SyntaxError)return {...result,kind:'invalid',error:'Invalid exported array field.'};if(!e.code)throw e;return {...result,kind:'invalid',error:e.message};}});return {headers:parsed.headers,mapping,rows};}
function exportCsv(rows){const quote=v=>'"'+safe(String(v??'')).replace(/"/g,'""')+'"';const data=[['CSV schema',...Object.values(FIELDS),'Assigned owner names','Outreach restriction (informational)','Source references (informational)'],...rows.map(r=>[SCHEMA,...Object.keys(FIELDS).map(k=>{const v=r[k]??(k==='lastContactedDate'&&r.lastOutboundAt?new Date(r.lastOutboundAt).toISOString():undefined);return Array.isArray(v)?JSON.stringify(v):k.endsWith('AtMs')&&Number.isFinite(v)?new Date(v).toISOString():v??'';}),r.assignedOwnerNames||'',r.doNotContact===true||r.suppressed===true?'Do not contact':'No consent granted by this export',JSON.stringify({sourceRef:r.sourceRef||null,linkedLeadIds:r.linkedLeadIds||[],linkedContactSources:r.linkedContactSources||[],lastImportId:r.lastImportId||null})])];return '\uFEFF'+data.map(r=>r.map(quote).join(',')).join('\r\n')+'\r\n';}
module.exports={SCHEMA,MAX_ROWS,MAX_BYTES,FIELDS,EXTRA,parse,detect,extras,plan,exportCsv};
