'use strict';

// Official, public organization channels. Selected by maintained service type
// and service area, never by Business email or a hard-coded customer identity.
const construction = [
  {key:'acds_contractors',kind:'business',name:'ACDS Contractor Opportunities',region:'Anne Arundel County, Maryland',serviceArea:{type:'county',locality:'Anne Arundel County',state:'Maryland'},industry:'construction opportunities',url:'https://acdsinc.org/work-with-us/contractor-opportunities/',signals:['home improvement','contractors'],email:'srice@acdsinc.org',useCase:'Review contractor qualification for property rehabilitation, repair and accessibility work.',reason:'The organization publicly uses home-improvement contractors. No specific project, award or homeowner buying intent is established.',cta:'Confirm contractor qualification and current bid-notice process'},
  {key:'hni_contractors',kind:'business',name:'Healthy Neighborhoods Contractor Network',region:'Baltimore City, Maryland',serviceArea:{type:'city',locality:'Baltimore',state:'Maryland'},industry:'construction opportunities',url:'https://healthyneighborhoods.org/electric-neighborhoods/',signals:['Potential Contractors','residential construction'],email:'wdlacovara@healthyneighborhoods.org',useCase:'Assess whether the contractor network accepts the Business’s general contracting services.',reason:'Public contractor-network channel. Energy-specialty requirements may not match the Business; confirm eligibility before any application. No active project or purchase intent is known.',cta:'Ask whether listed contracting services fit the network'},
  {key:'aawdc_customer',kind:'referral_partner',name:'Anne Arundel Workforce Development Corporation',region:'Anne Arundel County, Maryland',serviceArea:{type:'county',locality:'Anne Arundel County',state:'Maryland'},industry:'workforce partnerships',url:'https://aawdc.org/business/',signals:['recruitment','Anne Arundel'],email:'recruiter@aawdc.org',useCase:'Review employer recruitment services for construction or marketing positions.',reason:'Official employer recruitment channel; no individual worker availability or qualification is asserted.',cta:'Confirm employer requirements and recruitment options'},
  {key:'aacc_customer',kind:'referral_partner',name:'AACC Career and Employer Services',region:'Anne Arundel County, Maryland',serviceArea:{type:'county',locality:'Anne Arundel County',state:'Maryland'},industry:'workforce partnerships',url:'https://www.aacc.edu/about/administrative-offices/sarbanes-center-for-career-and-civic-engagement/',signals:['Employers','recruiting'],email:'careercenter@aacc.edu',useCase:'Assess the employer channel for appropriately described construction or marketing roles.',reason:'Organization-level recruitment partner, not a named or available worker.',cta:'Review employer posting and recruiting requirements'},
  {key:'baltimore_city_customer',kind:'referral_partner',name:'Baltimore City One-Stop Career Centers',region:'Baltimore City, Maryland',serviceArea:{type:'city',locality:'Baltimore',state:'Maryland'},industry:'workforce partnerships',url:'https://www.labor.md.gov/county/bacity/bacitybusor.shtml',signals:['Baltimore City','recruitment'],useCase:'Review public recruitment support before proposing a job opportunity.',reason:'Official workforce channel. Skills, transportation and availability of individual candidates are unknown.',cta:'Confirm appropriate recruitment channel'},
  {key:'baltimore_county_customer',kind:'referral_partner',name:'Baltimore County Business Services',region:'Baltimore County, Maryland',serviceArea:{type:'county',locality:'Baltimore County',state:'Maryland'},industry:'workforce partnerships',url:'https://baltimorecountymd.gov/departments/economic-development/business',signals:['recruit','workforce'],useCase:'Review recruitment partnerships for construction and marketing workforce.',reason:'Official workforce support, not an individual candidate or confirmed staffing commitment.',cta:'Review the official Business Services contact form'},
];
function select(profile) {
  const services=[...(profile.priorityServices||[]),...(profile.servicesOffered||[])].join(' ');
  return /\b(deck|decks|fence|fences|contracting|construction|remodeling|remodel|repair)\b/i.test(services) ? [...construction,...propertyManagers] : [];
}
const propertyManagers=[
 {key:'pmi_baltimore_vendors',kind:'business',name:'PMI Baltimore — Vendor Resources',region:'Baltimore County, Maryland',serviceArea:{type:'county',locality:'Baltimore County',state:'Maryland'},industry:'property management',opportunityType:'property_management',url:'https://www.baltimorespropertymanagement.com/vendors',signals:['Vendor Resources','Catonsville'],useCase:'Review the public vendor process for property maintenance services.',reason:'Property manager with a public vendor page and Baltimore County office. Contractor fit is plausible; no current project or purchase intent is established.',cta:'Review vendor requirements and ask whether your listed services fit',unknowns:'Managed property inventory, current projects, procurement terms and interest are unknown.'},
 {key:'aspen_vendors',kind:'business',name:'Aspen Property Management — Vendor Proposals',region:'Baltimore County, Maryland',serviceArea:{type:'county',locality:'Baltimore County',state:'Maryland'},industry:'HOA / community management',opportunityType:'property_management',url:'https://aspenpropertymgmt.com/join-our-team/',signals:['Baltimore County','Vendor'],email:'info@aspenpropertymgmt.com',useCase:'Assess the community-management vendor proposal process, including insurance and tax-document requirements.',reason:'The vendor form explicitly includes Baltimore County. This is a potential account fit, not a promised contract or active repair project.',cta:'Review the vendor form and confirm services and service footprint before sharing documents',unknowns:'Specific communities, available contracts, pricing and acceptance are unknown.'},
];
module.exports={select,construction,propertyManagers};
