'use strict';
// Public organization sources only. These are research starting points, not
// customers, interested applicants or permission to contact anyone.
module.exports = Object.freeze([
  {key:'jdw',kind:'business',name:'JDW Quality Landscape & Design',region:'Anne Arundel County, Maryland',serviceArea:{type:'county',locality:'Anne Arundel County',state:'Maryland'},industry:'landscaping',url:'https://jdwquality.com/contact/',signals:['Glen Burnie','Landscape'],phone:'443-782-5489',useCase:'A small authorized neighborhood campaign for landscape maintenance.',reason:'Published local residential landscaping service area; purchasing interest is unknown.'},
  {key:'acadia',kind:'business',name:'Acadia Landscaping',region:'Anne Arundel County, Maryland',serviceArea:{type:'county',locality:'Anne Arundel County',state:'Maryland'},industry:'landscaping',url:'https://www.acadialandscapinginc.com/',signals:['Anne Arundel','Landscaping'],email:'amhacadia@msn.com',phone:'410-859-0006',useCase:'Seasonal cleanup or landscape-maintenance campaign with route evidence.',reason:'Published residential and commercial services in the target county; campaign budget is unknown.'},
  {key:'capital',kind:'business',name:'Capital Landscaping',region:'Anne Arundel County, Maryland',serviceArea:{type:'county',locality:'Anne Arundel County',state:'Maryland'},industry:'landscaping',url:'https://www.capitallandscapingllc.com/contact',signals:['Anne Arundel','Landscaping'],email:'team@capitallandscapingllc.com',phone:'410-760-9096',useCase:'An authorized local lawn-care offer linked to a response page.',reason:'Published county service area and lawn-care services; current marketing need is unconfirmed.'},
  {key:'aacc',kind:'referral_partner',name:'AACC Sarbanes Center',region:'Anne Arundel County, Maryland',serviceArea:{type:'county',locality:'Anne Arundel County',state:'Maryland'},industry:'workforce partnerships',url:'https://www.aacc.edu/about/administrative-offices/sarbanes-center-for-career-and-civic-engagement/',signals:['Employers','recruiting'],email:'careercenter@aacc.edu',phone:'410-777-2053',useCase:'Ask whether their employer channel accepts clearly described local contract opportunities.',reason:'Published employer and student career services. Organization-level partner prospect, not an individual Scaler.'},
  {key:'aawdc',kind:'referral_partner',name:'Anne Arundel Workforce Development Corporation',region:'Anne Arundel County, Maryland',serviceArea:{type:'county',locality:'Anne Arundel County',state:'Maryland'},industry:'workforce partnerships',url:'https://aawdc.org/business/',signals:['recruitment','Anne Arundel'],email:'businesssolutions@aawdc.org',useCase:'Review eligibility for their recruitment channel before offering any Scaler opportunities.',reason:'Published recruitment services for local businesses. Participation and contractor eligibility remain unknown.'},
  {key:'baltimore_county',kind:'referral_partner',name:'Baltimore County Business Services',region:'Baltimore County, Maryland',serviceArea:{type:'county',locality:'Baltimore County',state:'Maryland'},industry:'workforce partnerships',url:'https://baltimorecountymd.gov/departments/economic-development/business',signals:['recruit','workforce'],useCase:'Ask about appropriate workforce referral channels and participation requirements.',reason:'Official workforce recruitment support. No individual worker availability or partnership is established.'},
]);
