'use strict';
const {test,before,after}=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {initializeApp,deleteApp}=require('firebase-admin/app'),{getAuth}=require('firebase-admin/auth'),{getFirestore,FieldValue,Timestamp}=require('firebase-admin/firestore');
const {createAuthority}=require('../functions-business-operations/authority'),{createService}=require('../functions-business-operations/service');
const {intelligence}=require('../functions-business-operations/campaign_planning');
const {hash}=require('./route_progress');
let app,db,auth,service;const now=Date.UTC(2026,8,26,18),area=[{latitude:39,longitude:-76},{latitude:39,longitude:-75.99},{latitude:39.01,longitude:-75.99},{latitude:39.01,longitude:-76}];
before(()=>{assert.ok(process.env.FIRESTORE_EMULATOR_HOST);assert.ok(process.env.FIREBASE_AUTH_EMULATOR_HOST);app=initializeApp({projectId:'demo-planner'},'planner');db=getFirestore(app);auth=getAuth(app);service=createService({db,FieldValue,authority:createAuthority({db,auth,FieldValue,Timestamp,project:'demo-planner',now:()=>now}),now:()=>now});});
after(async()=>{await db.terminate();await deleteApp(app);});
async function owner(){const uid='planner_'+crypto.randomUUID();await auth.createUser({uid,email:uid+'@example.test',emailVerified:true});await db.doc('users/'+uid).set({role:'business',active:true,email:uid+'@example.test'});for(const [type,v]of [['terms','terms-2026-08-v1'],['privacy','privacy-2026-08-v1']])await db.doc(`legalConsents/${uid}_${type}_${v}`).set({uid,agreementType:type,agreementVersion:v});return uid;}
const call=(b,operation,input={},uid=b)=>service.execute({auth:uid?{uid}:null,data:{businessId:b,operation,input,requestId:crypto.randomUUID()}});
const creation=(extra={})=>({requestId:crypto.randomUUID(),name:'Fixture marketing plan',description:'Synthetic planning only',campaignType:'flyer_distribution',executionMode:'own_team',...extra});
const create=async(b,extra={})=>(await call(b,'createCampaignPlan',creation(extra))).campaignId;
const context=(b,c)=>call(b,'campaignPlanningContext',{campaignId:c});
async function materials(b,c,extra={}){const cx=await context(b,c);return call(b,'saveCampaignMaterials',{campaignId:c,expectedPlanningVersion:cx.planningVersion,areaDigest:cx.areaDigest,materialQuantity:100,materialType:'flyer_distribution',materialSource:'business_provided',materialLogistics:{fulfillmentType:'no_materials_required'},scheduledStartAt:now+86400000,scheduledEndAt:now+90000000,...extra});}
async function schedule(b,c){const cx=await context(b,c);return call(b,'scheduleOwnTeamCampaign',{campaignId:c,expectedPlanningVersion:cx.planningVersion,areaDigest:cx.areaDigest,scheduledStartAt:now+86400000,scheduledEndAt:now+90000000});}
test('free owner completes intent → saved area → materials → own-team Schedule without financial artifacts',async()=>{
 const b=await owner(),c=await create(b);assert.equal((await context(b,c)).areaDigest,null);await assert.rejects(materials(b,c),{code:'failed-precondition'});
 await call(b,'saveCampaignPlanningArea',{campaignId:c,expectedPlanningVersion:1,serviceArea:area,serviceAreaName:'Controlled target'});await materials(b,c);await schedule(b,c);
 const cx=await context(b,c);assert.equal(cx.campaign.status,'own_team_scheduled');assert.equal(cx.editable,false);
 const item=(await db.doc(`businessOperations/${b}/items/${cx.campaign.scheduleItemId}`).get()).data();assert.equal(item.sourceKind,'own_team_campaign');assert.deepEqual(item.assignedPeople,[]);
 for(const col of ['campaignPayments','assignmentCompensations','earnings','trackingSessions','marketingHistory'])assert.equal((await db.collection(col).where('campaignId','==',c).get()).size,0);
 const map=await call(b,'campaignMapRecord',{campaignId:c});assert.deepEqual(map.territory,area);
 const loaded=await call(b,'load',{fromMs:now,toMs:now+3*86400000});assert.equal(loaded.items[0].campaignId,c);
});
test('creation retries share a stable identity and changed payload is rejected',async()=>{const b=await owner(),input=creation();const rs=await Promise.all([call(b,'createCampaignPlan',input),call(b,'createCampaignPlan',input)]);assert.equal(rs[0].campaignId,rs[1].campaignId);await assert.rejects(call(b,'createCampaignPlan',{...input,name:'Different'}),{code:'already-exists'});});
test('stale material review cannot survive a direct Zone geometry change',async()=>{const b=await owner(),c=await create(b,{initialServiceArea:area});await materials(b,c);await db.doc('campaignZones/z_'+c).set({businessId:b,campaignId:c,status:'unassigned',serviceArea:area});await assert.rejects(schedule(b,c),{code:'failed-precondition'});await materials(b,c);await schedule(b,c);});
test('changing saved area invalidates material review and preserves existing Zone boundaries',async()=>{const b=await owner(),c=await create(b,{initialServiceArea:area});const z=db.doc('campaignZones/z_'+c);await z.set({businessId:b,campaignId:c,status:'unassigned',serviceArea:area});await materials(b,c);await call(b,'saveCampaignPlanningArea',{campaignId:c,expectedPlanningVersion:2,serviceArea:area.map(p=>({...p,longitude:p.longitude+.001})),serviceAreaName:'New target'});assert.deepEqual((await z.get()).data().serviceArea,area);assert.equal((await context(b,c)).campaign.materialsAreaDigest,undefined);await assert.rejects(schedule(b,c),{code:'failed-precondition'});});
test('tenant, missing, signed-out, disabled and consent cases fail closed',async()=>{const b=await owner(),other=await owner(),c=await create(b);await assert.rejects(context(other,c),{code:'permission-denied'});await assert.rejects(call(b,'campaignPlanningContext',{campaignId:c},null),{code:'unauthenticated'});await assert.rejects(context(b,'missing'),{code:'not-found'});await auth.updateUser(b,{disabled:true});await assert.rejects(context(b,c),{code:'permission-denied'});await auth.updateUser(b,{disabled:false});await db.doc(`legalConsents/${b}_terms_terms-2026-08-v1`).delete();await assert.rejects(create(b),/legal_consent_required/);});
test('own-team cannot accept pay fields or financial bindings, including hidden ledger records',async()=>{const b=await owner(),c=await create(b,{initialServiceArea:area});await assert.rejects(materials(b,c,{basePay:100}),{code:'invalid-argument'});await materials(b,c);await db.doc('assignmentCompensations/contract_'+c).set({campaignId:c,businessId:b});await assert.rejects(schedule(b,c),{code:'failed-precondition'});});
test('marketplace material review records planned pay but does not fund or allow own-team schedule',async()=>{const b=await owner(),c=await create(b,{initialServiceArea:area,executionMode:'marketplace'});await materials(b,c,{basePay:50,bonus:50});const cx=await context(b,c);assert.equal(cx.campaign.basePay,50);assert.equal(cx.campaign.fundingStatus,undefined);assert.equal(cx.campaign.materialsAreaDigest,cx.areaDigest);await assert.rejects(schedule(b,c),{code:'failed-precondition'});});
test('optimistic writes and concurrent scheduling cannot duplicate Schedule records',async()=>{const b=await owner(),c=await create(b,{initialServiceArea:area});await materials(b,c);const results=await Promise.allSettled([schedule(b,c),schedule(b,c)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal((await db.collection(`businessOperations/${b}/items`).get()).size,1);await assert.rejects(call(b,'saveCampaignPlanningArea',{campaignId:c,expectedPlanningVersion:1,serviceArea:area}),{code:'aborted'});});
test('generic schedule completion cannot certify marketing or overwrite authoritative dates',async()=>{const b=await owner(),c=await create(b,{initialServiceArea:area});await materials(b,c);await schedule(b,c);await db.doc('businessSubscriptions/'+b).set({status:'active',plan:'growth',expiresAt:Timestamp.fromMillis(now+86400000)});const id=(await context(b,c)).campaign.scheduleItemId;await assert.rejects(call(b,'setItemStatus',{itemId:id,expectedVersion:1,status:'done'}),{code:'failed-precondition'});assert.equal((await db.doc(`businessOperations/${b}/items/${id}`).get()).data().status,'open');});
test('malformed/self-crossing areas and logistics are rejected; chosen area never silently shrinks',async()=>{const b=await owner();await assert.rejects(create(b,{initialServiceArea:[...area.slice(0,2)]}),{code:'failed-precondition'});const c=await create(b,{initialServiceArea:area});await assert.rejects(materials(b,c,{materialQuantity:-1}),{code:'invalid-argument'});await assert.rejects(materials(b,c,{materialLogistics:{fulfillmentType:'business_delivery'}}),{code:'invalid-argument'});assert.deepEqual((await context(b,c)).campaign.serviceArea,area);});
test('Census source records remain per-Zone estimates with no invented eligible points or suggested quantity',()=>{const p={status:'complete',geometryDigest:hash(area),residentialProperties:1234,metric:'Housing units in intersecting Census block groups',source:'Census',sourceVersion:'fixture',dataDate:'2024',limitations:['Not accessible doors']};const out=intelligence([{id:'a',serviceArea:area,targetPlanning:p},{id:'b',serviceArea:area,targetPlanning:p}]);assert.equal(out.zones[0].residentialProperties,1234);assert.equal(out.zones[1].source,'Census');assert.equal(out.eligibleDistributionPoints,null);assert.equal(out.suggestedQuantity,null);assert.equal(out.housingEstimate,null);assert.equal(intelligence([{id:'stale',serviceArea:area,targetPlanning:{...p,geometryDigest:'wrong'}}]).zones[0].residentialProperties,null);});
test('multi-day own-team plan remains on Schedule on its later overlapping days',async()=>{const b=await owner(),c=await create(b,{initialServiceArea:area}),end=now+6*86400000;await materials(b,c,{scheduledEndAt:end});const cx=await context(b,c);await call(b,'scheduleOwnTeamCampaign',{campaignId:c,expectedPlanningVersion:cx.planningVersion,areaDigest:cx.areaDigest,scheduledStartAt:now+86400000,scheduledEndAt:end});const later=await call(b,'load',{fromMs:now+4*86400000,toMs:now+5*86400000});assert.equal(later.items.length,1);assert.equal(later.items[0].campaignId,c);});
test('material pickup metadata survives callable save/reopen and outlying Zones block review',async()=>{const b=await owner(),c=await create(b,{initialServiceArea:area}),pickup=new Date(now+3600000).toISOString();await materials(b,c,{materialLogistics:{fulfillmentType:'scaler_pickup_print_shop',scheduledAt:pickup,location:'Controlled fixture shop',printingShopName:'Fixture printer',orderReference:'Fixture reference'}});const x=await context(b,c);assert.equal(x.campaign.materialHandoffScheduledAt,pickup);assert.equal(x.campaign.materialHandoffPrintingShopName,'Fixture printer');assert.equal(x.campaign.materialHandoffOrderReference,'Fixture reference');await db.doc('campaignZones/outside_'+c).set({businessId:b,campaignId:c,status:'unassigned',serviceArea:area.map(p=>({...p,longitude:p.longitude+1}))});await assert.rejects(materials(b,c),/outside the selected territory/);});
test('legacy analysis without current geometry stays unavailable, and exact-location types keep the existing workflow',async()=>{assert.equal(intelligence([{id:'missing',targetPlanning:{status:'complete',geometryDigest:'old'}}]).zones[0].status,'unavailable');const b=await owner();await assert.rejects(create(b,{campaignType:'dump_run'}),{code:'invalid-argument'});});
test('maintained Smart Zone workload is exposed only for matching saved geometry, never as material demand',()=>{const z={id:'smart',serviceArea:area,analysisStatus:'complete',serverZoneGeometryDigest:require('./operational_layer').zoneGeometryDigest(area),estimatedHomes:25,estimatedWorkMinutes:45,homeCountMethod:'smart_zone_conservative_density_v1',smartZonePolicyVersion:'fixture'};const out=intelligence([z]);assert.equal(out.zones[0].workloadMinutes,45);assert.equal(out.zones[0].residentialProperties,25);assert.equal(out.zones[0].metric,'Estimated properties (planning estimate)');assert.equal(out.suggestedQuantity,null);assert.equal(intelligence([{...z,serverZoneGeometryDigest:'stale'}]).zones[0].workloadMinutes,null);});
