'use strict';
if(!/^(localhost|127\.0\.0\.1):\d+$/.test(process.env.FIRESTORE_EMULATOR_HOST||''))throw Error('Local emulator required');
const {test,beforeEach,after}=require('node:test'),assert=require('node:assert/strict'),admin=require('firebase-admin');
const app=admin.initializeApp({projectId:'demo-social-grant'},'social-grant'),db=app.firestore(),{enroll}=require('./generation_operating_grant');
const at=1789909000000,expiresAt=1792454400000,input={db,businessUid:'scaledcircle',expectedPolicyId:'policy',expiresAt,maximumCostMicros:15000000,maximumConcepts:60,operator:'real-admin',authorizationReference:'fixture-authorized',now:()=>at};
beforeEach(async()=>{for(const c of ['visualGenerationGrants','socialManagedPolicies','businessBrandProfiles','providerConfigurations','entitlementAuditEvents'])await db.recursiveDelete(db.collection(c));await db.doc('socialManagedPolicies/scaledcircle').set({id:'policy',businessUid:'scaledcircle',status:'active',startsAt:at-1,endsAt:expiresAt});await db.doc('businessBrandProfiles/scaledcircle').set({approvedServiceCategories:['Business value']});await db.doc('providerConfigurations/generated-service-visuals').set({providerGenerationEnabled:true,modelSnapshot:'gpt-image-2-2026-04-21',size:'1536x1024',quality:'medium',betaCohortBusinessUids:['attractive-remodel']});});
after(()=>app.delete());
test('audited exact grant adds only enrolled workspace; retry does not renew or reset',async()=>{const first=await enroll(input),second=await enroll({...input,now:()=>at+1000});assert.equal(second.reused,true);assert.equal(second.startsAt,first.startsAt);assert.equal(first.expiresAt,expiresAt);assert.deepEqual((await db.doc('providerConfigurations/generated-service-visuals').get()).data().betaCohortBusinessUids,['attractive-remodel','scaledcircle']);assert.equal((await db.collection('entitlementAuditEvents').get()).size,1);});
test('policy mismatch, expiry extension, missing categories and grant top-up fail closed',async()=>{await assert.rejects(enroll({...input,expectedPolicyId:'wrong'}),/not_ready/);await assert.rejects(enroll({...input,expiresAt:expiresAt+1}),/not_ready/);await enroll(input);await assert.rejects(enroll({...input,maximumCostMicros:16000000}),/conflict/);await db.doc('businessBrandProfiles/scaledcircle').update({approvedServiceCategories:[]});await assert.rejects(enroll(input),/not_ready/);});
