"use strict";
const test=require("node:test");const assert=require("node:assert/strict");const lp=require("./landing_page");
test("no-asset draft is factual and complete",()=>{const d=lp.defaultDraft({businessName:"Harbor Landscaping",offering:"yard cleanup",serviceArea:"Annapolis"});assert.match(d.headline,/yard cleanup/);assert.equal(d.contactFields.includes("email"),true);assert.doesNotMatch(JSON.stringify(d),/award|review|licensed/i);});
test("sanitization rejects unsupported controls",()=>{assert.throws(()=>lp.sanitizeDraft({headline:"Hi",supportingText:"There",style:"raw_css"}),/invalid_landing_page_style/);});
test("public renderer escapes content and omits Flutter",()=>{const content=lp.sanitizeDraft({headline:"<script>x</script>",supportingText:"Safe",valuePoints:["Good"],contactFields:["name","email"]});const html=lp.renderPage({page:{publicSlug:"opaque"},version:{id:"v1",content}});assert.match(html,/&lt;script&gt;/);assert.doesNotMatch(html,/main\.dart\.js|flutter_bootstrap/);assert.match(html,/name="email"/);});
test("form requires identity and contact method",()=>{const version={content:{contactFields:["name","email","phone","message"]}};assert.throws(()=>lp.validateSubmission({name:"A"},version),/contact_required/);assert.equal(lp.validateSubmission({name:"A",email:"a@example.invalid"},version).name,"A");});
test("opaque slugs are non-enumerable and avoid ambiguous print glyphs",()=>{const s=lp.slug(()=>Buffer.alloc(18,7));assert.equal(lp.PUBLIC_SLUG_ALPHABET.length,32);assert.equal(s.length,29);assert.match(s,/^[23456789ABCDEFGHJKMNPQRSTUVWXYZ_]+$/);assert.doesNotMatch(s,/[01OIL]/);});
test("unavailable renderer is branded, safe, and omits Flutter",()=>{const html=lp.renderUnavailablePage();assert.match(html,/ScaledCircle/);assert.match(html,/This page is unavailable/);assert.match(html,/noindex,nofollow/);assert.doesNotMatch(html,/main\.dart\.js|flutter_bootstrap|<script/i);});
test("no-asset renderer is a complete responsive funnel",()=>{const content=lp.sanitizeDraft({headline:"Reliable yard cleanup in Annapolis",supportingText:"Tell us about the outdoor work you need.",valuePoints:["Seasonal cleanup","Property upkeep","A clear service conversation"],contactFields:["name","email","phone","message"]});const html=lp.renderPage({page:{publicSlug:"opaque"},version:{id:"v1",content}});for(const marker of ["hero-grid","value-grid","process-title","faq-title","conversion-grid","form-card","mid-cta"]){assert.match(html,new RegExp(marker));}assert.match(html,/@media\(max-width:820px\)/);assert.match(html,/@media\(max-width:420px\)/);assert.match(html,/aria-labelledby="contact-title"/);assert.match(html,/focus-visible/);assert.doesNotMatch(html,/main\.dart\.js|flutter_bootstrap|<script/i);});
test("all style presets produce distinct deterministic presentation",()=>{const rendered=new Map();for(const style of lp.STYLES){const content=lp.sanitizeDraft({headline:"Local service",supportingText:"Start with a clear request.",valuePoints:["Useful service"],style,contactFields:["name","email"]});const html=lp.renderPage({page:{publicSlug:"opaque"},version:{id:"v1",content}});assert.match(html,new RegExp(`<body class="${style}">`));rendered.set(style,html);}assert.equal(rendered.size,4);assert.notEqual(rendered.get("clean"),rendered.get("bold"));assert.notEqual(rendered.get("friendly"),rendered.get("premium"));});
test("renderer adds no unsupported Business claims",()=>{const content=lp.sanitizeDraft({headline:"Home service",supportingText:"Tell us what you need.",valuePoints:["Repairs"],contactFields:["name","email"]});const html=lp.renderPage({page:{publicSlug:"opaque"},version:{id:"v1",content}});assert.doesNotMatch(html,/award|licensed|guarantee|five.star|customer count|financing|same.day|response time/i);assert.match(html,/Submitting does not create a purchase/);});
test("success renderer is branded, responsive, and does not leak implementation details",()=>{const html=lp.renderSuccessPage({style:"friendly"});assert.match(html,/Your request is in/);assert.match(html,/class="friendly"/);assert.match(html,/Powered by ScaledCircle/);assert.match(html,/noindex,nofollow/);assert.doesNotMatch(html,/leadId|Firebase|Firestore|Function|stack|<script/i);});
test("landing inquiry email jobs use the shared outbound contract",()=>{const job=lp.outboundEmailJob({to:"  PERSON@Example.Invalid ",subject:"Request received",textBody:"Transactional confirmation",template:"landing_page_customer_confirmation",eventType:"landing_page.inquiry.confirmation",metadata:{landingPageId:"page"}});assert.equal(job.to,"person@example.invalid");assert.equal(job.status,"queued");assert.equal(job.attempts,0);assert.equal(job.fromAddress,"support@scaledcircle.com");assert.equal(job.replyTo,"support@scaledcircle.com");assert.equal(job.template,"landing_page_customer_confirmation");});

function memoryDb(seed={}){const docs=new Map(Object.entries(seed));let nextId=0;class Snap{constructor(ref){this.ref=ref;this.id=ref.id;this.exists=docs.has(ref.path);}data(){return docs.get(this.ref.path);}}class Ref{constructor(path){this.path=path;this.id=path.split("/").at(-1);}collection(name){return new Col(`${this.path}/${name}`);}async get(){return new Snap(this);}}class Query{constructor(path,field,value){this.path=path;this.field=field;this.value=value;this.maximum=Infinity;}limit(n){this.maximum=n;return this;}async get(){const prefix=`${this.path}/`;const found=[];for(const [path,data] of docs){if(path.startsWith(prefix)&&!path.slice(prefix.length).includes("/")&&data?.[this.field]===this.value)found.push(new Snap(new Ref(path)));}return{docs:found.slice(0,this.maximum)};}}class Col{constructor(path){this.path=path;}doc(id){return new Ref(`${this.path}/${id||`auto-${++nextId}`}`);}where(field,_op,value){return new Query(this.path,field,value);}}const db={collection:(name)=>new Col(name),runTransaction:async(fn)=>fn({get:(ref)=>ref.get(),create:(ref,data)=>{if(docs.has(ref.path))throw new Error("already_exists");docs.set(ref.path,data);},set:(ref,data,{merge}={})=>docs.set(ref.path,merge?{...(docs.get(ref.path)||{}),...data}:data),update:(ref,data)=>docs.set(ref.path,{...(docs.get(ref.path)||{}),...data})}),docs};return db;}

function landingSeed({trackingMode="off"}={}){const content=lp.sanitizeDraft({headline:"Published A",supportingText:"Current public copy",contactFields:["name","email","phone","message"]});return{"landingPages/page-a":{businessUid:"business-a",publicSlug:"PUBLIC_A",status:"published",trackingMode,publishedVersionId:"version-a",draftVersionId:"version-b",campaignId:null},"landingPages/page-a/versions/version-a":{content},"landingPages/page-a/versions/version-b":{content:{...content,headline:"Unpublished B"}},"users/business-a":{role:"business",businessName:"Harbor Services"}};}

test("submission transaction is retry-idempotent and tracking-off remains unattributed",async()=>{const db=memoryDb(landingSeed());const service=lp.createLandingPageService({db,FieldValue:{serverTimestamp:()=>"SERVER_TIME"},getAuthUser:async()=>({email:"owner@example.invalid",emailVerified:true})});const input={slug:"PUBLIC_A",version:"version-a",name:"Pat",email:"pat@example.invalid",message:"Estimate please"};const first=await service.submit(input,{ip:"127.0.0.1",requestIdentity:"request-one"});const replay=await service.submit(input,{ip:"127.0.0.1",requestIdentity:"request-two"});assert.equal(first.created,true);assert.equal(replay.created,false);assert.equal(first.leadId,replay.leadId);const paths=[...db.docs.keys()];assert.equal(paths.filter((p)=>p.startsWith("salesLeads/")).length,1);assert.equal(paths.filter((p)=>p.startsWith("salesActivities/")).length,1);assert.equal(paths.filter((p)=>p.startsWith("notifications/")).length,1);assert.equal(paths.filter((p)=>p.startsWith("outboundEmailJobs/")).length,2);assert.equal(paths.filter((p)=>p.startsWith("attributionConversions/")).length,0);const lead=db.docs.get(`salesLeads/${first.leadId}`);assert.equal(lead.attribution.landingPageVersionId,"version-a");assert.equal(lead.attribution.sourceDetail,"PUBLIC_A");});

test("phone-only inquiry queues no customer email and tracking-on uses the same lead",async()=>{const db=memoryDb(landingSeed({trackingMode:"first_party"}));const service=lp.createLandingPageService({db,FieldValue:{serverTimestamp:()=>"SERVER_TIME"},getAuthUser:async()=>({email:"owner@example.invalid",emailVerified:true})});await service.submit({slug:"PUBLIC_A",version:"version-a",name:"Phone Customer",phone:"555-0100",idempotencyKey:"phone-only"});const paths=[...db.docs.keys()];assert.equal(paths.filter((p)=>p.startsWith("salesLeads/")).length,1);assert.equal(paths.filter((p)=>p.startsWith("outboundEmailJobs/")).length,1);assert.equal(paths.filter((p)=>p.startsWith("attributionConversions/")).length,1);});

test("public input cannot select lead owner or Business email recipient",async()=>{const db=memoryDb(landingSeed());const service=lp.createLandingPageService({db,FieldValue:{serverTimestamp:()=>"SERVER_TIME"},getAuthUser:async()=>({email:"verified-owner@example.invalid",emailVerified:true})});const result=await service.submit({slug:"PUBLIC_A",version:"version-a",name:"Public",email:"visitor@example.invalid",ownerUid:"attacker",businessUid:"attacker",recipient:"attacker@example.invalid",idempotencyKey:"authority"});assert.equal(db.docs.get(`salesLeads/${result.leadId}`).ownerUid,"business-a");const businessJob=[...db.docs.entries()].find(([path])=>path.startsWith("outboundEmailJobs/landing-business_"))[1];assert.equal(businessJob.to,"verified-owner@example.invalid");});

test("saving a draft keeps the published version live and immutable",async()=>{const db=memoryDb(landingSeed());const service=lp.createLandingPageService({db,FieldValue:{serverTimestamp:()=>"SERVER_TIME"}});const saved=await service.saveDraft({pageId:"page-a",content:{headline:"Draft B",supportingText:"Tomorrow's public copy",contactFields:["name","email"]}}, {uid:"business-a",role:"business"});const page=db.docs.get("landingPages/page-a");assert.equal(page.status,"published");assert.equal(page.publishedVersionId,"version-a");assert.equal(page.draftVersionId,saved.versionId);assert.notEqual(page.draftVersionId,page.publishedVersionId);assert.equal(db.docs.get("landingPages/page-a/versions/version-a").content.headline,"Published A");const resolved=await service.resolve("PUBLIC_A");assert.equal(resolved.version.id,"version-a");assert.equal(resolved.version.content.headline,"Published A");});

test("republish advances only the published pointer and preserves the stable slug and history",async()=>{const db=memoryDb(landingSeed());const service=lp.createLandingPageService({db,FieldValue:{serverTimestamp:()=>"SERVER_TIME"},publicBaseUrl:"https://scaledcircle-staging.web.app"});const saved=await service.saveDraft({pageId:"page-a",content:{headline:"Published B",supportingText:"New public copy",contactFields:["name","email"]}}, {uid:"business-a",role:"business"});const result=await service.transition({pageId:"page-a",action:"publish"},{uid:"business-a",role:"business"});const page=db.docs.get("landingPages/page-a");assert.equal(result.publicSlug,"PUBLIC_A");assert.equal(page.publicSlug,"PUBLIC_A");assert.equal(page.status,"published");assert.equal(page.publishedVersionId,saved.versionId);assert.equal(db.docs.has("landingPages/page-a/versions/version-a"),true);const resolved=await service.resolve("PUBLIC_A");assert.equal(resolved.version.content.headline,"Published B");});

test("only explicit pause and archive transitions make a published page unavailable",async()=>{for(const action of ["pause","archive"]){const db=memoryDb(landingSeed());const service=lp.createLandingPageService({db,FieldValue:{serverTimestamp:()=>"SERVER_TIME"}});await service.transition({pageId:"page-a",action},{uid:"business-a",role:"business"});await assert.rejects(()=>service.resolve("PUBLIC_A"),/landing_page_unavailable/);assert.equal(db.docs.get("landingPages/page-a").publishedVersionId,"version-a");}});
