'use strict';
if(!/^(127\.0\.0\.1|localhost):\d+$/.test(process.env.FIRESTORE_EMULATOR_HOST||''))throw Error('Offline emulator only');
const {test,beforeEach,after}=require('node:test'),assert=require('node:assert/strict');
const {initializeApp,deleteApp}=require('firebase-admin/app'),{getFirestore,FieldValue}=require('firebase-admin/firestore');
const policy=require('./live_work_certification_policy'),{createService}=require('./live_work_certification'),gate=require('./live_work_certification_gate');
const {createStore}=require('./scaler_cashout_live_store'),legal=require('./legal_consent'),market=require('./market_rollout');
const app=initializeApp({projectId:'demo-scaledcircle'},'live-work-offline'),db=getFirestore(app),time=1789308000000;
const c={version:policy.VERSION,enabled:true,project:'scaled-circle',appEnv:'production',permitId:'single_permit_000001',businessUid:'business_owner_000001',scalerUid:'scaler_worker_000001',campaignId:'private_campaign_000001',zoneId:'private_zone_000001',baseCents:300,bonusCents:0,maximumChargeCents:360,issuedAt:time,expiresAt:time+86400000};
const location={address:'Founder-selected offline example work site',latitude:39,longitude:-76};
let service,clock,providerCalls;
const get=async p=>(await db.doc(p).get()).data();
beforeEach(async()=>{
 for(const collection of ['users','marketProfiles','marketRollout','legalConsents','liveWorkCertifications','campaigns','campaignZones','campaignApplications','assignmentCompensations','campaignCompletions','campaignPayments','campaignSettlements','wallets','walletTransactions','scalerTransfers','financialOperations','scalerCashoutIndex','scalerCashoutAllocations'])await db.recursiveDelete(db.collection(collection));
 clock=time;providerCalls=[];
 await db.doc(market.CONFIG).set(market.initialConfig());for(const [uid,role]of [[c.businessUid,'business'],[c.scalerUid,'scaler']]){await db.doc('users/'+uid).set({role,active:true});await db.doc('marketProfiles/'+uid).set({stateId:'us_census_tigerweb:state:24',selectionSource:'explicit_user_selection'});for(const type of role==='scaler'?['terms','privacy','scaler_work']:['terms','privacy'])await db.doc(`legalConsents/${uid}_${type}_${legal.AGREEMENTS[type]}`).set({uid,agreementType:type,agreementVersion:legal.AGREEMENTS[type],acceptedAt:1});}
 const stripe={paymentIntents:{retrieve:async()=>({id:'pi_actual',livemode:true,status:'succeeded',amount_received:360,currency:'usd',latest_charge:'ch_actual',metadata:{paymentId:'payment_actual',campaignId:c.campaignId,businessUid:c.businessUid}})},charges:{retrieve:async()=>({id:'ch_actual',livemode:true,paid:true,disputed:false,amount:360,amount_refunded:0,payment_intent:'pi_actual'})}};
 const photo=await require('sharp')({create:{width:100,height:100,channels:3,background:'red'}}).jpeg().toBuffer();
 const bucket={file:(path)=>({download:async()=>[photo],getMetadata:async()=>[{generation:'1',contentType:'image/jpeg',size:100,md5Hash:path.includes('before')?'beforeHash':'afterHash'}],copy:async()=>{},getSignedUrl:async()=>['https://example.test/private-evidence']})};
 service=createService({db,auth:{getUser:async()=>({disabled:false,emailVerified:true})},FieldValue,bucket,stripe,config:{project:'scaled-circle',appEnv:'production',paidWorkEnabled:'false',permit:c},quoteForCampaign:require('../functions-campaign-funding/campaign_funding_lifecycle').quoteForCampaign,now:()=>clock,fetchImpl:async()=>({ok:true,json:async()=>({features:[{attributes:{STATE:'24'}}]})})});
});
after(async()=>{await db.terminate();await deleteApp(app);});
const run=(uid,action,extra={})=>service.run(uid,{action,confirmation:true,...extra});
async function funded(){await run(c.businessUid,'create',{location});await db.doc('campaignPayments/payment_actual').set({paymentId:'payment_actual',campaignId:c.campaignId,businessId:c.businessUid,businessUid:c.businessUid,status:'paid',paidAt:1,stripeMode:'live',stripePaymentIntentId:'pi_actual',workerAmountCents:300,platformFeeCents:60,businessChargeCents:360,totalChargeCents:360,currency:'usd'});await db.doc('campaigns/'+c.campaignId).update({fundingStatus:'funded',fundingPaymentId:'payment_actual'});}
async function accepted(){await funded();await run(c.businessUid,'publish');await run(c.scalerUid,'apply');await run(c.businessUid,'assign');await run(c.scalerUid,'accept');}
async function submitted(){await accepted();const state=await service.get(c.scalerUid);await run(c.scalerUid,'submit',{notes:'Real-world work supplied only by Founder outside this offline test.',photos:['before','after'].map(purpose=>({purpose,path:`completionProofs/${c.campaignId}/${c.scalerUid}/${state.completionId}/${purpose}/photo.jpg`}))});}
test('read-only status creates no task; exact saved quote is $3 plus $0.60 and no Checkout is created',async()=>{assert.equal((await service.get(c.businessUid)).status,'not_created');assert.equal((await db.collection('campaigns').get()).size,0);const result=await run(c.businessUid,'create',{location});assert.equal(result.quote.totalChargeCents,360);assert.equal(result.quote.platformFeeCents,60);assert.equal(result.activeTrackingSessionId,null);assert.equal((await db.collection('campaignPayments').get()).size,0);assert.deepEqual(providerCalls,[]);});
test('only configured owner and Scaler can use one immutable task; no fake consent, public path or expired creation',async()=>{await assert.rejects(service.get('unrelated'));await assert.rejects(run(c.scalerUid,'create',{location}));await run(c.businessUid,'create',{location});await assert.rejects(run(c.businessUid,'create',{location:{...location,address:'Different location must not replace original'}}));assert.equal((await get('campaigns/'+c.campaignId)).marketplaceVisible,false);await db.doc(`legalConsents/${c.scalerUid}_scaler_work_${legal.AGREEMENTS.scaler_work}`).delete();await assert.rejects(service.get(c.scalerUid));clock=c.expiresAt+1;await assert.rejects(run(c.businessUid,'create',{location}));});
test('narrow funding authority permits only exact created task while ordinary paid work stays held',async()=>{await run(c.businessUid,'create',{location});const campaign=await get('campaigns/'+c.campaignId),input={actorUid:c.businessUid,campaignId:c.campaignId,campaign};assert.equal((await gate.assertFunding({db,quoteForCampaign:require('../functions-campaign-funding/campaign_funding_lifecycle').quoteForCampaign,input,project:'scaled-circle',raw:c,enabled:'false',now:clock})).certified,true);await assert.rejects(gate.assertFunding({db,quoteForCampaign:require('../functions-campaign-funding/campaign_funding_lifecycle').quoteForCampaign,input:{...input,campaign:{businessId:c.businessUid}},project:'scaled-circle',raw:c,enabled:'false',now:clock}));await db.doc('liveWorkCertifications/'+c.permitId).update({locationDigest:'changed'});await assert.rejects(gate.assertFunding({db,quoteForCampaign:require('../functions-campaign-funding/campaign_funding_lifecycle').quoteForCampaign,input,project:'scaled-circle',raw:c,enabled:'false',now:clock}));});
test('real application, assignment, explicit acceptance and physical proof required before Business settlement',async()=>{await funded();await assert.rejects(run(c.businessUid,'approve'));await assert.rejects(run(c.scalerUid,'accept'));await run(c.businessUid,'publish');await run(c.scalerUid,'apply');await assert.rejects(run(c.scalerUid,'assign'));await run(c.businessUid,'assign');await run(c.scalerUid,'accept');await assert.rejects(run(c.scalerUid,'submit',{notes:'No photos supplied'}));assert.equal((await db.collection('walletTransactions').get()).size,0);});
test('ordinary reserve settlement creates one real-earning chain; cash-out accepts it without GPS or TEST balances',async()=>{await submitted();const acceptedContract=await get('assignmentCompensations/'+c.zoneId);await run(c.businessUid,'approve');await run(c.businessUid,'approve');assert.equal((await db.collection('campaignSettlements').get()).size,1);assert.equal((await db.collection('walletTransactions').get()).size,1);assert.equal((await get('wallets/'+c.scalerUid)).availableBalance,3);assert.equal((await createStore(db).available(c.scalerUid)).availableCents,300);assert.deepEqual(await get('assignmentCompensations/'+c.zoneId),acceptedContract);assert.equal((await db.collection('trackingSessions').get()).size,0);assert.equal((await db.collection('financialOperations').get()).size,0);});
test('expiry prevents a new charge but cannot erase a funded accepted compensation obligation',async()=>{await submitted();clock=c.expiresAt+1;await run(c.businessUid,'approve');assert.equal((await get('wallets/'+c.scalerUid)).availableBalance,3);});
