'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const p=require('../functions-mobile-notifications/policy');
test('push identity carries no contact, money, provider or route details',()=>{const n={type:'business_email_reply',message:'Private customer at a private address $999',deepLink:{operationId:'secret'}};const m=p.message(n,'reply_123',{token:'device-secret'},'production');assert.deepEqual(m.data,{notificationId:'reply_123',environment:'production'});assert.equal(m.notification.body.includes('Private'),false);assert.equal(m.android.restrictedPackageName,'com.scaledcircle.app');assert.equal(m.android.notification.tag,m.apns.headers['apns-collapse-id']);});
test('cold prospects are in-app only; Growth briefs grouped; high-value replies immediate',()=>{assert.equal(p.policy({type:'agent_qualified_prospect'}),null);assert.equal(p.policy({type:'agent_daily_brief'}).immediate,false);assert.equal(p.policy({type:'business_email_reply'}).immediate,true);assert.equal(p.policy({type:'payout_failed'}).immediate,true);});
test('preferences preserve opt-out and account notices cannot be categorically disabled',()=>{assert.equal(p.preferences().enabled,false);assert.equal(p.preferences({growthDigest:false,categories:{money:false}}).growthDigest,false);assert.equal(p.preferences({categories:{money:false}}).categories.money,false);assert.equal(p.categories.includes('account'),false);assert.equal(p.policy({type:'security_notice'}).required,true);});
test('production/staging project binding fails closed',()=>{assert.equal(p.validEnvironment('scaled-circle','production'),true);assert.equal(p.validEnvironment('scaled-circle','staging'),false);assert.equal(p.validEnvironment('scaledcircle-staging','production'),false);assert.equal(p.validEnvironment('random','production'),false);});
test('only confirmed unusable tokens are removed; ambiguous sends not blindly retried',()=>{assert.equal(p.failure('messaging/registration-token-not-registered'),'invalid_device');assert.equal(p.failure('messaging/invalid-argument'),'uncertain');assert.equal(p.failure('messaging/server-unavailable'),'retryable');assert.equal(p.failure('messaging/third-party-auth-error'),'provider_configuration');});
const {signal}=require('../functions-mobile-notifications/signals');
test('actual reply event has one stable identity and no conversion inference; certification excluded',()=>{const source={businessId:'owner',operationId:'op1',providerMessageId:'provider1'};const a=signal('reply','owner/replies/provider1',null,source);assert.equal(a.identity,signal('reply','owner/replies/provider1',null,source).identity);assert.equal(a.type,'business_email_reply');assert.equal(a.deepLink.operationId,'op1');assert.equal(a.stage,undefined);assert.equal(signal('reply','id',null,{...source,certification:true}),null);});
test('submitted/reserved work and payout initiation never claim money sent',()=>{const a={kind:'scaler_cashout_v1',authorityVersion:'ProductionApprovedEarningCashoutV1',mode:'live',ownerId:'scaler'};assert.equal(signal('payout','operation',null,{...a,state:'reserved'}),null);assert.equal(signal('payout','operation',null,{...a,state:'completed'}),null);assert.equal(signal('payout','operation',null,{...a,state:'completed',settled:true,fundingTransferRecorded:true}).type,'payout_paid');assert.equal(signal('payout','operation',null,{...a,state:'payout_pending'}).type,'payout_processing');});
test('Social review does not assert approval; publication requires actual provider receipt',()=>{assert.equal(signal('social','quality',null,{businessUid:'owner',contentItemId:'item',readyToPublish:false}),null);assert.equal(signal('social','quality',null,{businessUid:'owner',contentItemId:'item',provider:'instagram',readyToPublish:true}).type,'social_drafts_ready');assert.equal(signal('published','job',null,{businessUid:'owner',status:'scheduled',customerApproval:true}),null);assert.equal(signal('published','job',null,{businessUid:'owner',status:'published',customerApproval:true,providerPostId:'actual'}).type,'social_post_published');});

test('Social notifications never guess a missing provider',()=>{assert.equal(signal('social','quality',null,{businessUid:'owner',contentItemId:'item',readyToPublish:true}),null);});
