"use strict";
const {test}=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const model=require('./social_story_model'),review=require('./social_instagram_story_review');
const {createPublisher,fingerprint}=require('./social_instagram_story_publisher');
function memory(){const rows=new Map();let tail=Promise.resolve();const doc=path=>({path,get:async()=>({exists:rows.has(path),data:()=>structuredClone(rows.get(path))})});return {rows,doc,runTransaction:fn=>{const p=tail.then(()=>fn({get:r=>r.get(),create:(r,v)=>{assert.equal(rows.has(r.path),false);rows.set(r.path,structuredClone(v));},update:(r,v)=>rows.set(r.path,{...rows.get(r.path),...structuredClone(v)})}));tail=p.catch(()=>{});return p;}};}
function fixture(){const bytes=Buffer.from('bounded Story'),sha256=crypto.createHash('sha256').update(bytes).digest('hex');
 const media=model.media({owner:'story-execution-test',provider:'instagram',sha256,sourceHashes:[sha256],width:1080,height:1920,mime:'image/jpeg',bytes:bytes.length,url:`https://scaledcircle.com/social/${sha256}.jpg`,renditionRecipe:'fixture',intentionalRendition:true,textBounds:{x:100,y:300,width:800,height:1000}});
 const plan=model.week({surface:'story',owner:media.owner,provider:'instagram',accountId:'123',startsAt:'2030-01-01T00:00:00Z',endsAt:'2030-01-08T00:00:00Z',timeZone:'America/New_York',items:['product_authority','business_value','two_sided_model'].map((pillar,i)=>({surface:'story',contentId:`publish${i}`,version:1,text:`Story ${i}`,pillar,media,scheduledFor:`2030-01-0${i+2}T00:00:00Z`,ctaBehavior:'profile_text'}))});
 const jobs=model.draftJobs(plan),approvalId='story_approval_'+'b'.repeat(64),docs=review.documents({plan,assets:[media,media,media]});
 const approval={id:approvalId,schemaVersion:'StoryApprovalV1',surface:'story',owner:plan.owner,provider:'instagram',accountId:'123',linkedPageId:'456',planId:plan.id,planDigest:plan.digest,jobIds:jobs.map(j=>j.id),items:plan.items,validFrom:plan.startsAt,validUntil:plan.endsAt,revokedAt:null,maximumEffects:{containers:3,mediaPublishCalls:3,publishedStories:3,totalCreateRequests:6}};
 docs['socialStoryApprovals/'+approvalId]=approval;docs['agentHealth/'+plan.owner]={killSwitchActive:false};
 docs[`socialConnections/${plan.owner}/providers/instagram`]={providerUserId:'123',linkedPageId:'456',handle:'fixture',tokenHealth:'healthy',environment:'production',grantedScopes:['instagram_basic','instagram_content_publish','pages_read_engagement']};
 docs['socialStoryPlans/'+plan.id]={...plan,executionEnabled:true};
 for(const j of jobs)Object.assign(docs['socialStoryJobs/'+j.id],{approvalId,status:'approved',publishingEnabled:true});
 Object.assign(docs[model.paths(plan.owner,'instagram').authority],{approvalId,publishingEnabled:true,killSwitchActive:false});
 let time=Date.parse(jobs[0].scheduledFor),posts=0,ready=true,lose=false;
 const config={planId:plan.id,digest:plan.digest,owner:plan.owner,accountId:'123',pageId:'456',handle:'fixture',approvalId,approvalFingerprint:fingerprint(approval),enabled:true};
 const credentials=async()=>({tokenType:'PAGE',accessToken:'fixture',owner:plan.owner,accountId:'123',linkedPageId:'456',scopes:docs[`socialConnections/${plan.owner}/providers/instagram`].grantedScopes});
 const fetchImpl=async(u,o)=>{if(u===media.url)return new Response(bytes,{headers:{'content-type':'image/jpeg'}});assert.equal(o.headers.Authorization,'Bearer fixture');if(o.method==='POST'){posts++;if(lose)throw Error('lost');return Response.json({id:u.endsWith('/media')?'700':'800'});}if(u.includes('/700?'))return Response.json({id:'700',status_code:ready?'FINISHED':'IN_PROGRESS'});if(u.includes('content_publishing_limit'))return Response.json({data:[{quota_usage:0,config:{quota_total:100,quota_duration:86400}}]});return Response.json({data:[{id:'800',media_product_type:'STORY'}]});};
 const db=memory();for(const[p,v]of Object.entries(docs))db.rows.set(p,structuredClone(v));
 return {db,docs,jobs,plan,config,args:{db,config,credentials,fetchImpl,now:()=>time},count:()=>posts,setTime:v=>time=v,setReady:v=>ready=v,setLose:()=>lose=true};
}
test('pinned scheduler discovers only three jobs and performs no future provider request',async()=>{const f=fixture();f.setTime(0);const p=createPublisher(f.args);assert.ok((await p.tick()).every(j=>j.state==='FUTURE'));assert.equal(f.count(),0);assert.equal((await p.inspect()).jobs.length,3);});
test('scheduled execution persists exactly one container, publication and receipt under replay/concurrency',async()=>{const f=fixture(),p=createPublisher(f.args);await Promise.all([p.tick(),p.tick()]);await p.tick();assert.equal(f.count(),2);const r=await p.inspect();assert.equal(r.jobs[0].receipts,1);assert.equal(r.jobs[1].steps,0);});
test('known container resumes while unknown outcome holds without duplicate POST',async()=>{const f=fixture(),p=createPublisher(f.args);f.setReady(false);await p.tick();assert.equal(f.count(),1);f.setReady(true);await p.tick();assert.equal(f.count(),2);const g=fixture();g.setLose();await createPublisher(g.args).tick();await createPublisher(g.args).tick();assert.equal(g.count(),1);});
test('global/channel/plan/job/deployment gates deny provider creates',async()=>{for(const gate of ['global','channel','plan','job','deployment']){const f=fixture();if(gate==='global')f.db.rows.get('agentHealth/'+f.plan.owner).killSwitchActive=true;if(gate==='channel')f.db.rows.get(model.paths(f.plan.owner,'instagram').authority).killSwitchActive=true;if(gate==='plan')f.db.rows.get('socialStoryPlans/'+f.plan.id).executionEnabled=false;if(gate==='job')f.db.rows.get('socialStoryJobs/'+f.jobs[0].id).publishingEnabled=false;if(gate==='deployment')f.config.enabled=false;await createPublisher(f.args).tick();assert.equal(f.count(),0,gate);}});
test('changed approval, version, Page identity and expired create window fail closed',async()=>{for(const gate of ['approval','version','page','expired']){const f=fixture();if(gate==='approval')f.db.rows.get('socialStoryApprovals/'+f.config.approvalId).validUntil='2040-01-01T00:00:00Z';if(gate==='version')f.db.rows.get('socialStoryVersions/'+f.jobs[0].versionId).text='changed';if(gate==='page')f.db.rows.get(`socialConnections/${f.plan.owner}/providers/instagram`).linkedPageId='999';if(gate==='expired')f.setTime(Date.parse(f.plan.endsAt));await createPublisher(f.args).tick().catch(()=>{});assert.equal(f.count(),0,gate);}});
test('Firestore emulator: concurrent scheduled workers and replay have exactly one provider effect per step',{skip:!process.env.FIRESTORE_EMULATOR_HOST},async()=>{
 assert.match(process.env.GCLOUD_PROJECT||'demo-scaledcircle',/^demo-/);const {Firestore}=require('firebase-admin/firestore');const db=new Firestore({projectId:'demo-scaledcircle'}),f=fixture();
 try{const batch=db.batch();for(const[p,v]of Object.entries(f.docs))batch.set(db.doc(p),v);await batch.commit();const p=createPublisher({...f.args,db});await Promise.all([p.tick(),p.tick()]);await p.tick();assert.equal(f.count(),2);assert.equal((await p.inspect()).jobs[0].receipts,1);await p.tick();assert.equal(f.count(),2);}finally{await db.terminate();}
});
