'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const {authorize}=require('../functions-social-operations/social_managed_creative');
const bounded=require('../functions-social-operations/social_bounded_authority');
function fixture(){
 const uid='managed_owner',now=1900000000000,planId='plan',input={itemId:'post',provider:'instagram',version:1};
 const plan={businessUid:uid,status:'approved',planVersion:1,approvedVersion:1,strategy:{services:['decks']}};
 const policy=bounded.createPolicy({uid,actorUid:uid,planId,plan,services:['decks'],destinations:['https://example.com/'],providers:['instagram'],startsAt:now,endsAt:now+86400000,now});
 const candidate={assetId:'asset',revisionId:'revision',jobId:'visual_job_abc',sha256:'d'.repeat(64),sourceSha256:'e'.repeat(64),preparation:{pixelCheck:'passed',checkedSha256:'d'.repeat(64),subjectQuality:{status:'passed',checkedSha256:'d'.repeat(64),reasons:[]}}};
 const prep='socialCreativePreparation/'+require('../functions-social-operations/social_creative_diversity').leaseId(uid,input),ar=`businessMediaLibraries/${uid}/mediaAssets/asset`,rr=ar+'/revisions/revision';
 const data={['socialManagedPolicies/'+uid]:policy,['socialContentPlans/'+planId]:plan,['businessSubscriptions/'+uid]:{plan:'managed_growth',status:'active',expiresAt:new Date(now+86400000)},['socialContentItems/post']:{businessUid:uid,planId,currentVersion:1},[prep]:{businessUid:uid,itemId:input.itemId,provider:input.provider,version:1,reviewCandidate:candidate},['agentHealth/'+uid]:{},['socialContentVersions/post_v1']:{goal:'Decks',variants:[{provider:'instagram',copy:'Explore decks for your home.',destinationUrl:'https://example.com/'}]},[ar]:{businessUid:uid,currentRevisionId:'revision'},[rr]:{businessUid:uid,origin:'generated_service_concept',createdBy:'creative-media-core',status:'ready',contentHash:candidate.sourceSha256,generationJobId:candidate.jobId,moderationStatus:'passed',moderation:{status:'passed',flags:[]},truthfulnessDisclosure:'Service concept, not completed work.',altText:'Deck design concept',approvalStatus:'pending'},['visualGenerationJobs/visual_job_abc']:{businessUid:uid,candidateAssetId:'asset',candidateRevisionId:'revision'}};
 const ref=p=>({path:p,collection:c=>({doc:id=>ref(p+'/'+c+'/'+id)})});
 const db={doc:ref,runTransaction:async fn=>{const writes=[];const result=await fn({get:async r=>({exists:r.path in data,data:()=>data[r.path]}),update:(r,v)=>writes.push(()=>{data[r.path]={...data[r.path],...v};}),create:(r,v)=>writes.push(()=>{assert(!data[r.path]);data[r.path]=v;})});writes.forEach(f=>f());return result;}};
 return {db,uid,input,policyId:policy.id,candidate,now,data,policy,prep,rr,ar};
}
test('passing creative uses auditable strategy authority exactly once without creating jobs',async()=>{const f=fixture();assert.deepEqual(await authorize(f),{reused:false});assert.deepEqual(await authorize(f),{reused:true});assert.equal(f.data[f.rr].authorizationSource,'approved_strategy');assert.equal(Object.keys(f.data).filter(k=>k.startsWith('socialManagedCreativeAudit/')).length,1);assert.equal(Object.keys(f.data).filter(k=>k.startsWith('socialGrowthJobs/')).length,0);});
for(const [name,mutate]of Object.entries({pause:f=>f.policy.status='paused',revision:f=>f.data['socialContentItems/post'].currentVersion=2,tenant:f=>f.data[f.rr].businessUid='other',quality:f=>f.candidate.preparation.subjectQuality.status='failed',hash:f=>f.candidate.preparation.subjectQuality.checkedSha256='wrong',moderation:f=>f.data[f.rr].moderation.flags.push('unsafe'),scope:f=>f.data['socialContentVersions/post_v1'].variants[0].destinationUrl='https://other.example/',claim:f=>f.data['socialContentVersions/post_v1'].variants[0].copy='We built decks for our happy customer.',hold:f=>f.data['agentHealth/'+f.uid].killSwitchActive=true}))test('rejects '+name+' without approval writes',async()=>{const f=fixture();mutate(f);await assert.rejects(authorize(f));assert.equal(f.data[f.rr].approvalStatus,'pending');});


