"use strict";
const {test}=require('node:test'), assert=require('node:assert/strict');
const model=require('./social_story_model'), review=require('./social_instagram_story_review');
function fixture(){
 const media=model.media({owner:'review-test',provider:'instagram',sha256:'a'.repeat(64),sourceHashes:['b'.repeat(64)],width:1080,height:1920,mime:'image/jpeg',bytes:100,url:`https://scaledcircle.com/social/${'a'.repeat(64)}.jpg`,renditionRecipe:'fixture',intentionalRendition:true,textBounds:{x:100,y:300,width:800,height:1000}});
 const plan=model.week({surface:'story',owner:'review-test',provider:'instagram',accountId:'123',startsAt:'2030-01-01T00:00:00Z',endsAt:'2030-01-08T00:00:00Z',timeZone:'America/New_York',items:['product_authority','business_value','two_sided_model'].map((pillar,i)=>({surface:'story',contentId:`review${i}`,version:1,text:`Story ${i}`,pillar,media,scheduledFor:`2030-01-0${i+2}T00:00:00Z`,ctaBehavior:'profile_text'}))});
 return {plan,assets:[media,media,media]};
}
function memory(){const rows=new Map();let tail=Promise.resolve();const doc=path=>({path,get:async()=>({exists:rows.has(path),data:()=>rows.get(path)})});return {rows,doc,runTransaction:fn=>{const run=tail.then(()=>fn({get:r=>r.get(),create:(r,v)=>{assert.equal(rows.has(r.path),false);rows.set(r.path,structuredClone(v));}}));tail=run.catch(()=>{});return run;}};}
test('review preparation is deterministic, atomic and cannot overwrite authority',async()=>{const f=fixture(),db=memory();const before=JSON.stringify(f);const r=await Promise.all([review.prepare(db,f),review.prepare(db,f)]);assert.equal(r[1].created,0);assert.equal(r[0].jobIds.length,3);assert.equal(JSON.stringify(f),before);assert.ok([...db.rows.keys()].every(p=>p.startsWith('socialStory')));const authority=model.paths(f.plan.owner,'instagram').authority;db.rows.get(authority).publishingEnabled=true;await assert.rejects(review.prepare(db,f));});
test('real review jobs hold on each stop control; negative bindings fail closed without writes',async()=>{const f=fixture(),db=memory();await review.prepare(db,f);db.rows.set('agentHealth/review-test',{killSwitchActive:false});const before=JSON.stringify([...db.rows]);const r=await review.inspect(db,f.plan.id);assert.equal(r.jobs.length,3);for(const j of r.jobs)assert.deepEqual(j.holds,['APPROVAL_REQUIRED','STORY_PAUSED','PUBLISHING_DISABLED','DEPLOYMENT_CREATE_DISABLED']);assert.ok(r.rehearsal.every(x=>x.wrongHashDenied&&x.wrongVersionDenied&&x.wrongIdentityDenied&&x.globalStopHeld&&x.unknownOutcome==='HOLD_UNKNOWN_OUTCOME'&&x.knownContainer==='RECONCILE_KNOWN_ID'));assert.equal(JSON.stringify([...db.rows]),before);});
test('measurement templates bind only Story receipt IDs and pre-expiration windows',()=>{const f=fixture(),docs=review.documents(f);const jobs=Object.entries(docs).filter(([p])=>p.startsWith('socialStoryJobs/')).map(([,v])=>v);for(const j of jobs){assert.equal(j.approvalId,null);assert.equal(j.measurement.versionId,j.versionId);assert.equal(j.measurement.mediaRevisionId,j.mediaRevisionId);assert.deepEqual(j.measurement.offsetsHours,[1,23]);assert.equal(j.measurement.providerIdSource,'verified_receipt_only');assert.equal(j.measurement.expiredStatus,'UNAVAILABLE');}});
test('Firestore emulator preparation concurrency and immutable replay',{skip:!process.env.FIRESTORE_EMULATOR_HOST},async()=>{assert.match(process.env.GCLOUD_PROJECT||'demo-scaledcircle',/^demo-/);const {Firestore}=require('firebase-admin/firestore');const db=new Firestore({projectId:'demo-scaledcircle'}),f=fixture();try{const rs=await Promise.all([review.prepare(db,f),review.prepare(db,f)]);assert.equal(rs.filter(r=>r.created>0).length,1);assert.equal((await review.inspect(db,f.plan.id)).jobs.length,3);assert.equal((await review.prepare(db,f)).created,0);}finally{await db.terminate();}});
