'use strict';
const {test,before,after}=require('node:test'),assert=require('node:assert/strict');
const admin=require('firebase-admin'),{createWorkspaceService}=require('./business_workspace'),{createBillingService}=require('./workspace_billing'),c=require('./subscription_contract'),{createSubscriptionSync}=require('./workspace_subscription_sync');
const {price}=require('./subscription_catalog.test');
let app,db,auth,n=0;
before(()=>{assert.match(process.env.FIRESTORE_EMULATOR_HOST||'',/^(127\.0\.0\.1|localhost):\d+$/);assert.match(process.env.FIREBASE_AUTH_EMULATOR_HOST||'',/^(127\.0\.0\.1|localhost):\d+$/);app=admin.initializeApp({projectId:'demo-catalog-billing'},'catalog-billing');db=app.firestore();auth=app.auth();});
after(async()=>{await db.terminate();await app.delete();});
async function fixture(selection={plan:'managed_growth',addons:Object.keys(c.ADDONS)}){
 const uid='catalog_owner_'+(++n);let now=Date.now();const periodStart=Math.floor(now/1000)-1000,periodEnd=periodStart+2592000;
 await auth.createUser({uid,email:uid+'@example.test',emailVerified:true});
 await db.doc('privateProductAccess/'+uid).set({businessId:uid,status:'approved',products:['managed_growth','business_assistant','lead_generation_research','growth_department'],expiresAtMillis:now+365*86400000});await db.doc('users/'+uid).set({role:'business',active:true,email:uid+'@example.test'});
 for(const [type,version]of [['terms','terms-2026-08-v1'],['privacy','privacy-2026-08-v1']])await db.doc(`legalConsents/${uid}_${type}_${version}`).set({uid,agreementType:type,agreementVersion:version,acceptedAt:admin.firestore.Timestamp.now()});
 const chosen=c.selectionTerms(selection),providers=Object.fromEntries(Object.keys(c.ITEMS).map(id=>[price(id).id,price(id)]));
 let provider={id:'sub_'+uid,livemode:true,customer:'cus_'+uid,status:'active',cancel_at_period_end:false,metadata:{firebaseUid:uid,...c.selectionMetadata(chosen)},items:{data:chosen.items.map(id=>({id:'si_'+id,quantity:1,price:price(id),current_period_start:periodStart,current_period_end:periodEnd}))},schedule:null};
 await db.doc('wallets/'+uid).set({stripeCustomerId:provider.customer,stripeSubscriptionId:provider.id,balance:1234});await db.doc('businessSubscriptions/'+uid).set({plan:chosen.plan,status:'active',expiresAt:admin.firestore.Timestamp.fromMillis(periodEnd*1000),source:'stripe',stripeSubscriptionId:provider.id});
 await db.doc('campaigns/'+uid).set({businessId:uid,status:'open',fundingStatus:'funded'});await db.doc('assignmentCompensations/'+uid).set({baseAmountCents:1500,immutable:true});
 const schedules=new Map(),effects={creates:0,updates:0,releases:0,subscriptions:0,previews:0};let loseUpdate=false,loseRelease=false,loseCreate=false;
 const stripe={prices:{retrieve:async id=>providers[id]},products:{retrieve:async id=>{const p=Object.values(providers).find(p=>p.product===id);return {id,livemode:true,active:true,metadata:p.metadata};}},subscriptions:{retrieve:async()=>structuredClone(provider),update:async(id,params)=>{assert.equal(id,provider.id);effects.subscriptions++;provider={...provider,...params};return structuredClone(provider);}},
  invoices:{createPreview:async params=>{effects.previews++;assert.equal(params.subscription,provider.id);const items=params.subscription_details.items.filter(i=>!i.deleted);const total=items.reduce((s,i)=>s+providers[i.price].unit_amount,0);return {currency:'usd',amount_due:total,total};}},
  subscriptionSchedules:{create:async(params,options)=>{assert.equal(params.from_subscription,provider.id);assert.ok(options.idempotencyKey);effects.creates++;const s={id:'sched_'+uid,subscription:provider.id,customer:provider.customer,livemode:true,status:'active',metadata:{},current_phase:{start_date:periodStart,end_date:periodEnd},phases:[]};schedules.set(s.id,s);provider.schedule=s.id;if(loseCreate)throw Error("lost_create_response");return structuredClone(s);},retrieve:async id=>structuredClone(schedules.get(id)),update:async(id,params,options)=>{assert.ok(options.idempotencyKey);effects.updates++;const s={...schedules.get(id),...params};schedules.set(id,s);if(loseUpdate)throw Error('lost_response');return structuredClone(s);},release:async(id,params,options)=>{assert.ok(options.idempotencyKey);effects.releases++;const s=schedules.get(id);s.status='released';s.released_subscription=s.subscription;s.subscription=null;provider.schedule=null;if(loseRelease)throw Error('lost_release_response');return structuredClone(s);}}};
 const planForPrice=id=>Object.keys(c.ITEMS).find(item=>price(item).id===id),config={environment:'production',planForPrice};
 const sync=createSubscriptionSync({db,FieldValue:admin.firestore.FieldValue,Timestamp:admin.firestore.Timestamp,...config});
 const workspace=createWorkspaceService({db,auth,FieldValue:admin.firestore.FieldValue,Timestamp:admin.firestore.Timestamp,origin:'https://example.test'});
 const service=createBillingService({db,FieldValue:admin.firestore.FieldValue,workspace,stripe:()=>stripe,planForPrice,priceForPlan:id=>price(id).id,sync,validateProvider:s=>c.certifySubscription(stripe,s,config),validatePrice:id=>c.certifyPrice(stripe,id,{...config,requireActive:true}),now:()=>now});
 return {uid,service,stripe,effects,schedules,get provider(){return provider;},loseUpdate(){loseUpdate=true;},loseRelease(){loseRelease=true;},loseCreate(){loseCreate=true;},async activate(keepSchedule=false){const phase=schedules.get(provider.schedule).phases[1];now=phase.start_date*1000+1;provider={...provider,schedule:keepSchedule?provider.schedule:null,metadata:phase.metadata,items:{data:phase.items.map((i,n)=>({id:'si_new_'+n,quantity:1,price:providers[i.price],current_period_start:phase.start_date,current_period_end:phase.start_date+2592000}))}};await sync(provider,'evt_phase_'+uid);},async unchanged(){assert.equal((await db.doc('wallets/'+uid).get()).data().balance,1234);assert.equal((await db.doc('campaigns/'+uid).get()).data().fundingStatus,'funded');assert.equal((await db.doc('assignmentCompensations/'+uid).get()).data().baseAmountCents,1500);}};
}
test('individual items switch to one $2,000 bundle at renewal; old paid access is retained',async()=>{const f=await fixture(),q=await f.service.preview({uid:f.uid,selection:{bundle:c.BUNDLE}});assert.equal(q.monthlyCents,200000);assert.equal(q.chargeNowCents,0);assert.equal(q.effectiveAtMs,f.provider.items.data[0].current_period_end*1000);const r=await f.service.change({uid:f.uid,action:'changeSelection',quoteId:q.quoteId,requestId:'bundle_request_123456'});assert.equal(r.price,2097);assert.equal(r.scheduledChange.monthlyCents,200000);assert.equal(f.provider.items.data.length,3);assert.equal(f.schedules.values().next().value.phases[1].items.length,1);await f.activate();const e=(await db.doc('businessSubscriptions/'+f.uid).get()).data();assert.equal(e.monthlyCents,200000);assert.equal(e.bundle,c.BUNDLE);assert.equal(e.seatLimit,10);assert.deepEqual(e.addons,Object.keys(c.ADDONS));assert.equal(f.effects.creates,1);assert.equal(f.effects.subscriptions,0);await f.unchanged();});
test('bundle can become a base plus selected add-on; future seat reservation clears only at reconciliation',async()=>{const f=await fixture({bundle:c.BUNDLE}),q=await f.service.preview({uid:f.uid,selection:{plan:'growth',addons:['business_assistant']}});assert.equal(q.monthlyCents,69800);await f.service.change({uid:f.uid,action:'changeSelection',quoteId:q.quoteId,requestId:'leave_bundle_123456'});assert.equal((await db.doc('businessWorkspaces/'+f.uid).get()).data().pendingSeatLimit,3);await f.activate();const e=(await db.doc('businessSubscriptions/'+f.uid).get()).data();assert.equal(e.plan,'growth');assert.equal(e.seatLimit,3);assert.equal(e.bundle,null);assert.deepEqual(e.addons,['business_assistant']);assert.ok(!e.productEntitlements.includes('lead_generation_research'));assert.equal((await db.doc('businessWorkspaces/'+f.uid).get()).data().pendingSeatLimit,undefined);await f.unchanged();});
test('remove one add-on at billing boundary without canceling membership or losing current paid access',async()=>{const f=await fixture(),q=await f.service.preview({uid:f.uid,selection:{plan:'managed_growth',addons:['business_assistant']}});assert.equal(q.monthlyCents,139800);await f.service.change({uid:f.uid,action:'changeSelection',quoteId:q.quoteId,requestId:'remove_addon_123456'});assert.equal(f.provider.items.data.length,3);assert.equal(f.provider.cancel_at_period_end,false);await f.activate();assert.equal(f.provider.items.data.length,2);assert.equal((await f.service.get({uid:f.uid})).price,1398);await f.unchanged();});
test('scheduled change can be withdrawn, then normal cancel/reactivate remains available',async()=>{const f=await fixture(),q=await f.service.preview({uid:f.uid,selection:{bundle:c.BUNDLE}});await f.service.change({uid:f.uid,action:'changeSelection',quoteId:q.quoteId,requestId:'schedule_for_cancel_1'});await f.service.change({uid:f.uid,action:'cancelScheduledChange',requestId:'cancel_schedule_12345'});assert.equal(f.effects.releases,1);assert.equal(f.provider.items.data.length,3);await f.service.change({uid:f.uid,action:'cancel',requestId:'cancel_membership_123'});assert.equal(f.provider.cancel_at_period_end,true);await f.service.change({uid:f.uid,action:'reactivate',requestId:'reactivate_member_123'});assert.equal(f.provider.cancel_at_period_end,false);await f.unchanged();});
test('same request is idempotent and lost schedule update reply reconciles without another write',async()=>{const f=await fixture(),q=await f.service.preview({uid:f.uid,selection:{bundle:c.BUNDLE}}),request={uid:f.uid,action:'changeSelection',quoteId:q.quoteId,requestId:'lost_reply_request_123'};f.loseUpdate();await assert.rejects(f.service.change(request),{code:'unavailable'});assert.equal(f.effects.updates,1);const result=await f.service.change(request);assert.equal(result.scheduledChange.monthlyCents,200000);const again=await f.service.change(request);assert.equal(again.duplicate,true);assert.equal(f.effects.updates,1);assert.equal(f.effects.creates,1);await f.unchanged();});
test('non-billing member, wrong owner quote and expired quote cannot schedule a change',async()=>{const f=await fixture(),other=await fixture();await assert.rejects(f.service.preview({uid:other.uid,businessId:f.uid,selection:{bundle:c.BUNDLE}}),{code:'permission-denied'});const q=await f.service.preview({uid:f.uid,selection:{bundle:c.BUNDLE}});await assert.rejects(other.service.change({uid:other.uid,action:'changeSelection',quoteId:q.quoteId,requestId:'other_owner_request_1'}),{code:'failed-precondition'});await db.doc('businessBillingQuotes/'+q.quoteId).update({expiresAtMs:1});await assert.rejects(f.service.change({uid:f.uid,action:'changeSelection',quoteId:q.quoteId,requestId:'expired_request_12345'}),{code:'failed-precondition'});assert.equal(f.effects.creates,0);});

test('bundle cannot use legacy single-base proration endpoint',async()=>{const f=await fixture({bundle:c.BUNDLE});await assert.rejects(f.service.preview({uid:f.uid,plan:'growth'}),{code:'failed-precondition'});await assert.rejects(f.service.change({uid:f.uid,action:'changePlan',plan:'growth',requestId:'legacy_bundle_123456'}),{code:'failed-precondition'});assert.equal(f.effects.subscriptions,0);});
test('lost release response reconciles once and clears future seat reservation',async()=>{const f=await fixture({bundle:c.BUNDLE}),q=await f.service.preview({uid:f.uid,selection:{plan:'growth'}});await f.service.change({uid:f.uid,action:'changeSelection',quoteId:q.quoteId,requestId:'future_seats_1234567'});f.loseRelease();const r={uid:f.uid,action:'cancelScheduledChange',requestId:'release_lost_1234567'};await assert.rejects(f.service.change(r),{code:'unavailable'});await f.service.change(r);assert.equal(f.effects.releases,1);assert.equal((await db.doc('businessWorkspaces/'+f.uid).get()).data().pendingSeatLimit,undefined);await f.unchanged();});
test('unknown schedule creation remains HOLD and does not repeat provider create',async()=>{const f=await fixture(),q=await f.service.preview({uid:f.uid,selection:{bundle:c.BUNDLE}});f.loseCreate();const r={uid:f.uid,action:'changeSelection',quoteId:q.quoteId,requestId:'unknown_create_123456'};await assert.rejects(f.service.change(r),{code:'unavailable'});await assert.rejects(f.service.change(r),{code:'unavailable'});assert.equal(f.effects.creates,1);assert.equal(f.effects.updates,0);await f.unchanged();});
test('wrong-mode schedule fails closed and special terms are not silently overwritten',async()=>{const f=await fixture();f.provider.discounts=['di_existing'];await assert.rejects(f.service.preview({uid:f.uid,selection:{bundle:c.BUNDLE}}),{code:'failed-precondition'});f.provider.discounts=[];const q=await f.service.preview({uid:f.uid,selection:{bundle:c.BUNDLE}});await f.service.change({uid:f.uid,action:'changeSelection',quoteId:q.quoteId,requestId:'mode_schedule_123456'});f.schedules.get(f.provider.schedule).livemode=false;await assert.rejects(f.service.get({uid:f.uid}),{code:'failed-precondition'});assert.equal(f.effects.creates,1);});
test('concurrent selection requests reserve only one schedule and owner-inclusive seats reject over-capacity',async()=>{const f=await fixture(),q=await f.service.preview({uid:f.uid,selection:{bundle:c.BUNDLE}});const results=await Promise.allSettled(['concurrent_a_123456','concurrent_b_123456'].map(requestId=>f.service.change({uid:f.uid,action:'changeSelection',quoteId:q.quoteId,requestId})));assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(f.effects.creates,1);const g=await fixture({bundle:c.BUNDLE});await db.doc('businessWorkspaces/'+g.uid+'/members/member1').set({uid:'member1',status:'active',seatIndex:1});const small=await g.service.preview({uid:g.uid,selection:{plan:'starter'}});await assert.rejects(g.service.change({uid:g.uid,action:'changeSelection',quoteId:small.quoteId,requestId:'seat_limit_12345678'}),{code:'failed-precondition'});assert.equal(g.effects.creates,0);});

test('cancellation remains available after the bundle phase starts without waiting another month',async()=>{const f=await fixture(),q=await f.service.preview({uid:f.uid,selection:{bundle:c.BUNDLE}});await f.service.change({uid:f.uid,action:'changeSelection',quoteId:q.quoteId,requestId:'phase_for_cancel_1234'});await f.activate(true);await f.service.change({uid:f.uid,action:'cancel',requestId:'cancel_applied_123456'});assert.equal(f.effects.releases,1);assert.equal(f.effects.subscriptions,1);assert.equal(f.provider.items.data[0].price.id,price(c.BUNDLE).id);assert.equal(f.provider.cancel_at_period_end,true);await f.unchanged();});
