'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),c=require('./subscription_contract');
function price(item,environment='production'){
 const data=c.ITEMS[item],kind=data.kind,scope=kind==='BASE_PLAN'?'membership':kind==='ADD_ON'?'addon':'bundle';
 return {id:'price_'+item.replaceAll('_',''),type:'recurring',active:true,livemode:environment==='production',currency:'usd',unit_amount:data.cents,billing_scheme:'per_unit',product:`scaledcircle_${kind==='BASE_PLAN'?'workspace':item}_${environment}_v1`,recurring:{interval:'month',interval_count:1,usage_type:'licensed'},metadata:{plan:item,purpose:`workspace_${scope}_${environment}_v1`,catalog_kind:kind,entitlements:data.entitlements.join(','),seats:String(data.seats)}};
}
const config={environment:'production',requireActive:true,planForPrice:id=>Object.keys(c.ITEMS).find(k=>price(k).id===id)};
function subscription(selection){const chosen=c.selectionTerms(selection);return {id:'sub_local',livemode:true,metadata:{firebaseUid:'business',...c.selectionMetadata(chosen)},items:{data:chosen.items.map(item=>({id:'si_'+item,quantity:1,price:price(item),current_period_end:Math.floor(Date.now()/1000)+86400}))}};}
for(const [name,selection,total,seats]of [
 ['Growth',{plan:'growth'},29900,3],['Growth + Assistant',{plan:'growth',addons:['business_assistant']},69800,3],
 ['Scale + Research',{plan:'scale',addons:['lead_generation_research']},119800,5],
 ['Managed Growth',{plan:'managed_growth'},99900,10],
 ['Managed Growth + Assistant',{plan:'managed_growth',addons:['business_assistant']},139800,10],
 ['Managed Growth + Research',{plan:'managed_growth',addons:['lead_generation_research']},169800,10],
 ['all three individual',{plan:'managed_growth',addons:['business_assistant','lead_generation_research']},209700,10],
 ['Growth Department',{bundle:'growth_department'},200000,10],
 ])test(`${name}: provider-derived total ${total}, seats ${seats}`,()=>{const s=subscription(selection),t=c.providerTerms(s,config);assert.equal(t.monthlyCents,total);assert.equal(t.seats,seats);assert.equal(t.plan,selection.plan||'managed_growth');if(name==='Managed Growth')assert.deepEqual(t.entitlements,['managed_growth']);});
test('bundle savings are $97/month and $1,164/year; same three entitlements',()=>{const individual=c.selectionTerms({plan:'managed_growth',addons:Object.keys(c.ADDONS)}),bundle=c.selectionTerms({bundle:c.BUNDLE});assert.equal(individual.monthlyCents-bundle.monthlyCents,9700);assert.equal((individual.monthlyCents-bundle.monthlyCents)*12,116400);assert.deepEqual(individual.entitlements.sort(),bundle.entitlements.sort());assert.deepEqual(bundle.items,['growth_department']);});
test('duplicate components, multiple base plans, add-on-only and bundle-plus-items fail closed',()=>{
 for(const selection of [{addons:['business_assistant']},{plan:'growth',addons:['business_assistant','business_assistant']},{bundle:c.BUNDLE,addons:['business_assistant']},{bundle:c.BUNDLE,plan:'growth'},{plan:'growth',addons:['lead_generation_outreach']}])assert.throws(()=>c.selection(selection));
 const full=subscription({bundle:c.BUNDLE});full.items.data.push(subscription({plan:'managed_growth'}).items.data[0]);assert.throws(()=>c.providerTerms(full,config),/double_billing/);
 const multi=subscription({plan:'starter'});multi.items.data.push(subscription({plan:'growth'}).items.data[0]);assert.throws(()=>c.providerTerms(multi,config),/base_plan_required/);
});
test('each configured LIVE item rejects TEST, amount/product/purpose/kind/entitlement/seat drift',()=>{for(const item of Object.keys(c.ITEMS)){const p=price(item);assert.equal(c.priceTerms(p,config).plan,item);for(const modified of [{livemode:false},{unit_amount:p.unit_amount+1},{product:'other'},{metadata:{...p.metadata,purpose:'wrong'}},{metadata:{...p.metadata,catalog_kind:'OTHER'}}])assert.throws(()=>c.priceTerms({...p,...modified},config));if(c.ITEMS[item].kind!=='BASE_PLAN')for(const key of ['entitlements','seats'])assert.throws(()=>c.priceTerms({...p,metadata:{...p.metadata,[key]:'wrong'}},config));}});
test('provider certification reads every item and rejects duplicate product charges',async()=>{const s=subscription({plan:'managed_growth',addons:Object.keys(c.ADDONS)}),seen=[];const stripe={prices:{retrieve:async id=>{seen.push(id);return Object.keys(c.ITEMS).map(i=>price(i)).find(p=>p.id===id);}},products:{retrieve:async id=>{const p=Object.keys(c.ITEMS).map(i=>price(i)).find(p=>p.product===id);return {id,livemode:true,active:true,metadata:p.metadata};}}};await c.certifySubscription(stripe,s,config);assert.equal(seen.length,3);s.items.data.push(s.items.data[1]);await assert.rejects(c.certifySubscription(stripe,s,config));});
test('paid product access is separate from base seats and never grants outreach',()=>{const e=require('./subscription_entitlements');const record={plan:'managed_growth',status:'active',expiresAt:new Date(Date.now()+86400000),source:'stripe',addons:[],productEntitlements:['managed_growth']};assert.equal(e.hasActiveProductEntitlement(record,'business_assistant'),false);for(const p of Object.keys(c.ADDONS)){const granted={...record,addons:[p],productEntitlements:[p]};assert.equal(e.hasActiveProductEntitlement(granted,p),true);assert.equal(e.hasActiveProductEntitlement({...granted,status:'canceled'},p),false);assert.equal(e.hasActiveProductEntitlement({...granted,source:'client'},p),false);}assert.equal(e.hasActiveProductEntitlement({...record,addons:['lead_generation_outreach'],productEntitlements:['lead_generation_outreach']},'lead_generation_outreach'),false);});
module.exports={price,subscription,config};
test('configured base prices reject changed explicit seat or entitlement metadata',()=>{for(const plan of Object.keys(c.PLANS)){const p=price(plan);for(const patch of [{seats:'99'},{entitlements:'business_assistant'}])assert.throws(()=>c.priceTerms({...p,metadata:{...p.metadata,...patch}},config),/binding_mismatch/);}});
