// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbL53AGBKdblOW-jNr4tfX5zonhvdxOW0',
    appId: '1:1010956217112:web:87cfda2a5b0b6e58e70c6d',
    messagingSenderId: '1010956217112',
    projectId: 'scaled-circle',
    authDomain: 'scaled-circle.firebaseapp.com',
    storageBucket: 'scaled-circle.firebasestorage.app',
    measurementId: 'G-9VY50190LG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7Nb3oDg8puAwxask_6kb-V4hZSqxJWKo',
    appId: '1:1010956217112:android:3fbf4db1c555e9f9e70c6d',
    messagingSenderId: '1010956217112',
    projectId: 'scaled-circle',
    storageBucket: 'scaled-circle.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO1uKhShn-b08X26x0ubhpZPoyJ-ZlCv0',
    appId: '1:1010956217112:ios:0c1a12a1424128b9e70c6d',
    messagingSenderId: '1010956217112',
    projectId: 'scaled-circle',
    storageBucket: 'scaled-circle.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO1uKhShn-b08X26x0ubhpZPoyJ-ZlCv0',
    appId: '1:1010956217112:ios:0c1a12a1424128b9e70c6d',
    messagingSenderId: '1010956217112',
    projectId: 'scaled-circle',
    storageBucket: 'scaled-circle.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbL53AGBKdblOW-jNr4tfX5zonhvdxOW0',
    appId: '1:1010956217112:web:554cd6da8d17481ae70c6d',
    messagingSenderId: '1010956217112',
    projectId: 'scaled-circle',
    authDomain: 'scaled-circle.firebaseapp.com',
    storageBucket: 'scaled-circle.firebasestorage.app',
    measurementId: 'G-RK6CYZKR39',
  );
}
